/* Die Karten fuer Wavelength: gegensaetzliche Begriffspaare.
   Jede Karte ist [links, rechts]. Der linke Begriff liegt am Anfang der
   Skala (Wert 0), der rechte am Ende (Wert 100).

   Gute Paare sind solche, bei denen man ueber Zwischenstufen streiten kann -
   "kalt/heiss" funktioniert, "wahr/falsch" nicht, weil es dazwischen nichts
   gibt. */
const KARTEN=[
  ["kalt","heiß"],
  ["leise","laut"],
  ["langsam","schnell"],
  ["klein","groß"],
  ["billig","teuer"],
  ["alt","neu"],
  ["dunkel","hell"],
  ["weich","hart"],
  ["leicht","schwer"],
  ["schmutzig","sauber"],
  ["trocken","nass"],
  ["leer","voll"],
  ["kurz","lang"],
  ["dünn","dick"],
  ["flach","tief"],
  ["stumpf","scharf"],
  ["unbekannt","berühmt"],
  ["unwichtig","wichtig"],
  ["harmlos","gefährlich"],
  ["hässlich","schön"],
  ["langweilig","spannend"],
  ["einfach","kompliziert"],
  ["unhöflich","höflich"],
  ["faul","fleißig"],
  ["schüchtern","selbstbewusst"],
  ["ernst","albern"],
  ["streng","nachsichtig"],
  ["sparsam","großzügig"],
  ["pessimistisch","optimistisch"],
  ["chaotisch","ordentlich"],
  ["spontan","geplant"],
  ["stur","nachgiebig"],
  ["unterschätzt","überschätzt"],
  ["überbewertet","unterbewertet"],
  ["unbequem","bequem"],
  ["ungesund","gesund"],
  ["schädlich","nützlich"],
  ["nutzlos","unverzichtbar"],
  ["peinlich","beeindruckend"],
  ["verpönt","angesehen"],
  ["uncool","cool"],
  ["kitschig","stilvoll"],
  ["altmodisch","modern"],
  ["schlicht","protzig"],
  ["praktisch","hübsch"],
  ["günstig","luxuriös"],
  ["Fastfood","Feinkost"],
  ["herzhaft","süß"],
  ["mild","scharf"],
  ["fade","würzig"],
  ["Frühstück","Abendessen"],
  ["Snack","ganze Mahlzeit"],
  ["Alltagsessen","Festessen"],
  ["Wasser","Hochprozentiges"],
  ["Kindergetränk","Erwachsenengetränk"],
  ["Katzenmensch","Hundemensch"],
  ["Stadtmensch","Landmensch"],
  ["Frühaufsteher","Nachteule"],
  ["Einzelgänger","Rudeltier"],
  ["Kopfmensch","Bauchmensch"],
  ["Sparer","Ausgeber"],
  ["Zuschauer","Mitmacher"],
  ["Zuhörer","Redner"],
  ["Realist","Träumer"],
  ["Angeber","Untertreiber"],
  ["Perfektionist","Pragmatiker"],
  ["Gewohnheitstier","Abenteurer"],
  ["Kindheitserinnerung","Zukunftsmusik"],
  ["Vergangenheit","Zukunft"],
  ["kurzlebige Mode","zeitloser Klassiker"],
  ["Eintagsfliege","Legende"],
  ["Anfänger","Meister"],
  ["Amateur","Profi"],
  ["Hobby","Beruf"],
  ["Pflicht","Vergnügen"],
  ["Arbeit","Freizeit"],
  ["Alltag","Ausnahme"],
  ["Routine","Abenteuer"],
  ["Sicherheit","Risiko"],
  ["Vorsicht","Wagemut"],
  ["Regel","Ausnahme"],
  ["Ordnung","Freiheit"],
  ["Tradition","Fortschritt"],
  ["privat","öffentlich"],
  ["geheim","allgemein bekannt"],
  ["Nische","Massenphänomen"],
  ["Geheimtipp","Touristenfalle"],
  ["Insiderwissen","Allgemeinwissen"],
  ["kompliziert erklärt","kindgerecht erklärt"],
  ["Fachbegriff","Alltagswort"],
  ["Theorie","Praxis"],
  ["Idee","Umsetzung"],
  ["Plan","Zufall"],
  ["Talent","harte Arbeit"],
  ["Glück","Können"],
  ["Zufall","Absicht"],
  ["unterhaltsam","lehrreich"],
  ["Kunst","Handwerk"],
  ["Kitsch","Kunst"],
  ["Kinderfilm","Erwachsenenfilm"],
  ["Komödie","Drama"],
  ["seicht","tiefgründig"],
  ["Blockbuster","Arthouse"],
  ["Fortsetzung","Original"],
  ["Buch","Verfilmung"],
  ["Ohrwurm","Kunstwerk"],
  ["Partymusik","Musik zum Zuhören"],
  ["Radiohit","Geheimtipp"],
  ["Instrument","Stimme"],
  ["live","aus der Konserve"],
  ["Brettspiel","Videospiel"],
  ["Glücksspiel","Denkspiel"],
  ["Kinderspiel","Expertenspiel"],
  ["kurze Partie","Langzeitprojekt"],
  ["allein","zu vielen"],
  ["Sport","Bewegung"],
  ["Wettkampf","Spaß"],
  ["Kraft","Ausdauer"],
  ["Mannschaftssport","Einzelsport"],
  ["Zuschauersport","Mitmachsport"],
  ["Sommerurlaub","Winterurlaub"],
  ["Pauschalreise","Rucksacktour"],
  ["nah","weit weg"],
  ["Berge","Meer"],
  ["Zelt","Hotel"],
  ["Sehenswürdigkeit","Geheimtipp"],
  ["Großstadt","Dorf"],
  ["Norden","Süden"],
  ["Ausland","Inland"],
  ["Fahrrad","Auto"],
  ["öffentliche Verkehrsmittel","eigenes Auto"],
  ["Kleinwagen","Luxuskarosse"],
  ["sparsam","durstig"],
  ["Alltagsauto","Traumauto"],
  ["Neuwagen","Oldtimer"],
  ["Werkzeug","Spielzeug"],
  ["Gebrauchsgegenstand","Deko"],
  ["Wegwerfartikel","Erbstück"],
  ["Massenware","Handarbeit"],
  ["Plastik","Holz"],
  ["Antiquität","Neuheit"],
  ["Wohnzimmer","Keller"],
  ["aufgeräumt","gemütlich"],
  ["Altbau","Neubau"],
  ["Mietwohnung","Eigenheim"],
  ["minimalistisch","vollgestellt"],
  ["Schulfach","Hobby"],
  ["Note","Verständnis"],
  ["Auswendiglernen","Begreifen"],
  ["Frontalunterricht","Gruppenarbeit"],
  ["Hausaufgabe","Freizeit"],
  ["Bewerbungsgespräch","Freundschaftsgespräch"],
  ["Chef","Kollege"],
  ["E-Mail","Anruf"],
  ["Großraumbüro","Einzelbüro"],
  ["Homeoffice","Büro"],
  ["Meeting","stille Arbeit"],
  ["Nebenjob","Lebensaufgabe"],
  ["gut bezahlt","erfüllend"],
  ["Smalltalk","tiefes Gespräch"],
  ["Bekannter","bester Freund"],
  ["Nachricht","Besuch"],
  ["Kompliment","Kritik"],
  ["Ehrlichkeit","Höflichkeit"],
  ["Nachgeben","Streiten"],
  ["Geschenk","Geste"],
  ["Überraschung","Wunschzettel"],
  ["Handgemacht","Gekauft"],
  ["Kindergeburtstag","Silvesterparty"],
  ["Familienfeier","Freundesabend"],
  ["Feiertag","normaler Tag"],
  ["Vorfreude","Ereignis"],
  ["Sommer","Winter"],
  ["Regen","Sonne"],
  ["Frühling","Herbst"],
  ["morgens","abends"],
  ["Wochentag","Wochenende"],
  ["Nacht","Tag"],
  ["Minute","Stunde"],
  ["gestern","in zehn Jahren"],
  ["Gerücht","Tatsache"],
  ["Meinung","Wissen"],
  ["Bauchgefühl","Statistik"],
  ["Aberglaube","Wissenschaft"],
  ["Märchen","Geschichtsbuch"],
  ["harmlose Notlüge","dreiste Lüge"],
  ["Fehler","Katastrophe"],
  ["Missgeschick","Skandal"],
  ["Kleinigkeit","große Sache"],
  ["Ärgernis","Drama"],
  ["Haustier","Wildtier"],
  ["niedlich","furchteinflößend"],
  ["Nutztier","Kuscheltier"],
  ["Insekt","Säugetier"],
  ["Aquarium","Safari"],
  ["analog","digital"],
  ["Papier","Bildschirm"],
  ["Brief","Kurznachricht"],
  ["offline","ständig online"],
  ["Fernsehen","Streaming"],
  ["Radio","Podcast"],
  ["Werbung","Inhalt"],
  ["Schlagzeile","Artikel"],
  ["Handy","Computer"],
  ["Tastatur","Touchscreen"],
  ["App","Webseite"],
  ["kostenlos","Abo"],
  ["Open Source","gekaufte Software"],
  ["Prototyp","fertiges Produkt"],
  ["schnell gebaut","sorgfältig gebaut"],
  ["Funktion","Aussehen"],
  ["Standardlösung","Maßanfertigung"],
  ["unangenehme Wahrheit","angenehme Lüge"],
  ["Verantwortung","Freiheit"],
  ["Geduld","Tatendrang"],
  ["Zurückhaltung","Durchsetzungskraft"],
  ["Bescheidenheit","Stolz"],
  ["Mitleid","Bewunderung"],
  ["Angst","Respekt"],
  ["Nervosität","Vorfreude"],
  ["Wut","Enttäuschung"],
  ["Langeweile","Entspannung"],
  ["Stress","Anspannung"],
  ["Kindheit","Erwachsensein"],
  ["Naivität","Erfahrung"],
  ["Unschuld","Berechnung"],
  ["Quatsch","Genie"],
  ["Zufallstreffer","Meisterleistung"],
  ["überflüssig","lebensnotwendig"],
  ["nice to have","Grundbedürfnis"],
  ["Luxusproblem","echtes Problem"],
  ["Bagatelle","Notfall"],
];
