/* Die Karten fuer Wavelength: gegensaetzliche Begriffspaare, nach Themen
   sortiert. Jede Karte ist [links, rechts, Thema]. Der linke Begriff liegt am
   Anfang der Skala (Wert 0), der rechte am Ende (Wert 100).

   Gute Paare sind solche, bei denen man ueber die Zwischenstufen streiten
   kann - "kalt/heiss" funktioniert, "wahr/falsch" nicht, weil es dazwischen
   nichts gibt. Der Host waehlt im Warteraum aus, welche Themen im Spiel sind. */
const THEMEN=[
  {id:"allgemein",name:"Allgemein",emoji:"\ud83c\udfaf"},
  {id:"humor",name:"Humor & Peinlich",emoji:"\ud83d\ude2c"},
  {id:"essen",name:"Essen & Trinken",emoji:"\ud83c\udf7d\ufe0f"},
  {id:"medien",name:"Filme, Musik & Serien",emoji:"\ud83c\udfac"},
  {id:"alltag",name:"Alltag & Dinge",emoji:"\ud83c\udfe0"},
  {id:"menschen",name:"Menschen & Gefühle",emoji:"\ud83d\udc65"},
  {id:"welt",name:"Orte & Unterwegs",emoji:"\ud83c\udf0d"},
  {id:"technik",name:"Technik & Internet",emoji:"\ud83d\udcf1"}
];

const KARTEN=[

  /* --- allgemein --- */
  ["gut","schlecht","allgemein"],
  ["kalt","heiß","allgemein"],
  ["seltsam","normal","allgemein"],
  ["bunt","farblos","allgemein"],
  ["fühlt sich gut an","fühlt sich schlecht an","allgemein"],
  ["unverzichtbar","verzichtbar","allgemein"],
  ["teuer","billig","allgemein"],
  ["häufig","selten","allgemein"],
  ["berühmt","unbekannt","allgemein"],
  ["hell","dunkel","allgemein"],
  ["leise","laut","allgemein"],
  ["langsam","schnell","allgemein"],
  ["klein","groß","allgemein"],
  ["alt","neu","allgemein"],
  ["weich","hart","allgemein"],
  ["leicht","schwer","allgemein"],
  ["kurz","lang","allgemein"],
  ["dünn","dick","allgemein"],
  ["flach","tief","allgemein"],
  ["stumpf","scharf","allgemein"],
  ["unwichtig","wichtig","allgemein"],
  ["harmlos","gefährlich","allgemein"],
  ["hässlich","schön","allgemein"],
  ["langweilig","spannend","allgemein"],
  ["einfach","kompliziert","allgemein"],
  ["überschätzt","unterschätzt","allgemein"],
  ["nutzlos","nützlich","allgemein"],
  ["schmutzig","sauber","allgemein"],
  ["trocken","nass","allgemein"],
  ["leer","voll","allgemein"],

  /* --- humor --- */
  ["Kalauer","schwarzer Humor","humor"],
  ["Furz","Rülpser","humor"],
  ["Wortwitz","Slapstick","humor"],
  ["aus Versehen cool","bemüht cool","humor"],
  ["betrunken geschrieben","nüchtern bereut","humor"],
  ["Modeunfall","perfektes Outfit","humor"],
  ["peinliches Schweigen","zu viel erzählt","humor"],
  ["Socken in Sandalen","barfuß","humor"],
  ["überschätzte Waffe","unterschätzte Waffe","humor"],
  ["sieht nicht aus wie ein Mensch","sieht aus wie ein Mensch","humor"],
  ["peinlich","beeindruckend","humor"],
  ["uncool","cool","humor"],
  ["kitschig","stilvoll","humor"],
  ["Fremdscham","Mitgefühl","humor"],
  ["harmlose Notlüge","dreiste Lüge","humor"],
  ["Missgeschick","Skandal","humor"],
  ["Kleinigkeit","große Sache","humor"],
  ["Ärgernis","Drama","humor"],
  ["Quatsch","Geniestreich","humor"],
  ["Zufallstreffer","Meisterleistung","humor"],
  ["verpönt","angesehen","humor"],
  ["albern","todernst","humor"],
  ["Flachwitz","feiner Humor","humor"],
  ["Aufschneider","Tiefstapler","humor"],
  ["Schadenfreude","Mitleid","humor"],
  ["Witz über sich selbst","Witz über andere","humor"],
  ["Ironie","ernst gemeint","humor"],
  ["Cringe","charmant","humor"],
  ["keiner lacht","alle lachen","humor"],
  ["harmloser Streich","gemeiner Streich","humor"],

  /* --- essen --- */
  ["hohes Suchtpotenzial","geringes Suchtpotenzial","essen"],
  ["Kalorienbombe","kalorienarm","essen"],
  ["geschmacksintensiv","geschmacksneutral","essen"],
  ["guter Pizzabelag","schlechter Pizzabelag","essen"],
  ["schmeckt gut","schmeckt schlecht","essen"],
  ["sauber zu essen","Sauerei beim Essen","essen"],
  ["scharf","mild","essen"],
  ["Gemüse","Obst","essen"],
  ["gute Süßigkeit","schlechte Süßigkeit","essen"],
  ["angenehme Konsistenz","unangenehme Konsistenz","essen"],
  ["herzhaft","süß","essen"],
  ["fade","würzig","essen"],
  ["Frühstück","Abendessen","essen"],
  ["Snack","ganze Mahlzeit","essen"],
  ["Alltagsessen","Festessen","essen"],
  ["Fastfood","Feinkost","essen"],
  ["Wasser","Hochprozentiges","essen"],
  ["Kindergetränk","Erwachsenengetränk","essen"],
  ["warm serviert","kalt serviert","essen"],
  ["Vorspeise","Nachtisch","essen"],
  ["Beilage","Hauptsache","essen"],
  ["selbst gekocht","bestellt","essen"],
  ["gesund","ungesund","essen"],
  ["billig und satt","teuer und wenig","essen"],
  ["Imbiss","Sternerestaurant","essen"],
  ["sättigt lange","sofort wieder hungrig","essen"],
  ["teilt man","behält man für sich","essen"],
  ["mit den Händen","mit Besteck","essen"],
  ["zum Frühstück vertretbar","niemals zum Frühstück","essen"],
  ["riecht besser als es schmeckt","schmeckt besser als es riecht","essen"],

  /* --- medien --- */
  ["guter Film","schlechter Film","medien"],
  ["die dunkle Seite","die helle Seite","medien"],
  ["Abenteuerfilm","Actionfilm","medien"],
  ["guter Schauspieler","schlechter Schauspieler","medien"],
  ["gute Musik","schlechte Musik","medien"],
  ["überschätzter Musiker","unterschätzter Musiker","medien"],
  ["gute Serie","schlechte Serie","medien"],
  ["überschätztes Buch","unterschätztes Buch","medien"],
  ["guter Disney-Charakter","böser Disney-Charakter","medien"],
  ["Film war besser","Buch war besser","medien"],
  ["Blockbuster","Arthouse","medien"],
  ["Fortsetzung","Original","medien"],
  ["seicht","tiefgründig","medien"],
  ["Kinderfilm","Erwachsenenfilm","medien"],
  ["Komödie","Drama","medien"],
  ["Ohrwurm","Kunstwerk","medien"],
  ["Partymusik","Musik zum Zuhören","medien"],
  ["Radiohit","Geheimtipp","medien"],
  ["live","aus der Konserve","medien"],
  ["Instrument","Stimme","medien"],
  ["Schurke mit Stil","Schurke zum Fürchten","medien"],
  ["Held","Antiheld","medien"],
  ["zum Weinen","zum Lachen","medien"],
  ["einmal schauen","immer wieder schauen","medien"],
  ["Serie am Stück","Woche für Woche","medien"],
  ["Buch","Hörbuch","medien"],
  ["Untertitel","Synchronisation","medien"],
  ["Klassiker","Neuerscheinung","medien"],
  ["Soundtrack besser als der Film","Film besser als der Soundtrack","medien"],
  ["guter Film mit schlechtem Ende","schlechter Film mit gutem Ende","medien"],

  /* --- alltag --- */
  ["praktisch","hübsch","alltag"],
  ["altmodisch","modern","alltag"],
  ["schlicht","protzig","alltag"],
  ["günstig","luxuriös","alltag"],
  ["unbequem","bequem","alltag"],
  ["Wegwerfartikel","Erbstück","alltag"],
  ["Massenware","Handarbeit","alltag"],
  ["Plastik","Holz","alltag"],
  ["Antiquität","Neuheit","alltag"],
  ["Gebrauchsgegenstand","Deko","alltag"],
  ["Werkzeug","Spielzeug","alltag"],
  ["Wohnzimmer","Keller","alltag"],
  ["aufgeräumt","gemütlich","alltag"],
  ["Altbau","Neubau","alltag"],
  ["Mietwohnung","Eigenheim","alltag"],
  ["minimalistisch","vollgestellt","alltag"],
  ["Bargeld","Karte","alltag"],
  ["sparen","ausgeben","alltag"],
  ["reparieren","neu kaufen","alltag"],
  ["Ordnung","Freiheit","alltag"],
  ["Routine","Abenteuer","alltag"],
  ["Pflicht","Vergnügen","alltag"],
  ["Arbeit","Freizeit","alltag"],
  ["Alltag","Ausnahme","alltag"],
  ["morgens","abends","alltag"],
  ["Wochentag","Wochenende","alltag"],
  ["Sommer","Winter","alltag"],
  ["Frühling","Herbst","alltag"],
  ["Regen","Sonne","alltag"],
  ["Nacht","Tag","alltag"],

  /* --- menschen --- */
  ["schüchtern","selbstbewusst","menschen"],
  ["streng","nachsichtig","menschen"],
  ["sparsam","großzügig","menschen"],
  ["pessimistisch","optimistisch","menschen"],
  ["chaotisch","ordentlich","menschen"],
  ["spontan","geplant","menschen"],
  ["stur","nachgiebig","menschen"],
  ["faul","fleißig","menschen"],
  ["unhöflich","höflich","menschen"],
  ["ernst","verspielt","menschen"],
  ["Katzenmensch","Hundemensch","menschen"],
  ["Stadtmensch","Landmensch","menschen"],
  ["Frühaufsteher","Nachteule","menschen"],
  ["Einzelgänger","Rudeltier","menschen"],
  ["Kopfmensch","Bauchmensch","menschen"],
  ["Zuhörer","Redner","menschen"],
  ["Realist","Träumer","menschen"],
  ["Perfektionist","Pragmatiker","menschen"],
  ["Gewohnheitstier","Abenteurer","menschen"],
  ["Zuschauer","Mitmacher","menschen"],
  ["Smalltalk","tiefes Gespräch","menschen"],
  ["Bekannter","bester Freund","menschen"],
  ["Nachricht","Besuch","menschen"],
  ["Kompliment","Kritik","menschen"],
  ["Ehrlichkeit","Höflichkeit","menschen"],
  ["nachgeben","streiten","menschen"],
  ["Angst","Respekt","menschen"],
  ["Nervosität","Vorfreude","menschen"],
  ["Wut","Enttäuschung","menschen"],
  ["Langeweile","Entspannung","menschen"],

  /* --- welt --- */
  ["Berge","Meer","welt"],
  ["Stadt","Land","welt"],
  ["Fensterplatz","Gangplatz","welt"],
  ["Norden","Süden","welt"],
  ["Zelt","Hotel","welt"],
  ["Pauschalreise","Rucksacktour","welt"],
  ["nah","weit weg","welt"],
  ["Sehenswürdigkeit","Geheimtipp","welt"],
  ["Großstadt","Dorf","welt"],
  ["Ausland","Inland","welt"],
  ["Sommerurlaub","Winterurlaub","welt"],
  ["Fahrrad","Auto","welt"],
  ["öffentliche Verkehrsmittel","eigenes Auto","welt"],
  ["Kleinwagen","Luxuskarosse","welt"],
  ["Neuwagen","Oldtimer","welt"],
  ["Automatik","Handschaltung","welt"],
  ["fahren","mitfahren","welt"],
  ["schnell","sparsam","welt"],
  ["Elektro","Benzin","welt"],
  ["Stau","freie Fahrt","welt"],
  ["bekanntes Reiseziel","unbekanntes Reiseziel","welt"],
  ["warmes Land","kaltes Land","welt"],
  ["Strand","Wald","welt"],
  ["viel zu früh am Flughafen","auf den letzten Drücker","welt"],
  ["Koffer","Rucksack","welt"],
  ["alles durchgeplant","alles offen","welt"],

  /* --- technik --- */
  ["analog","digital","technik"],
  ["Papier","Bildschirm","technik"],
  ["Brief","Kurznachricht","technik"],
  ["offline","ständig online","technik"],
  ["Fernsehen","Streaming","technik"],
  ["Radio","Podcast","technik"],
  ["Werbung","Inhalt","technik"],
  ["Schlagzeile","Artikel","technik"],
  ["Handy","Computer","technik"],
  ["Tastatur","Touchscreen","technik"],
  ["App","Webseite","technik"],
  ["kostenlos","Abo","technik"],
  ["iPhone","Android","technik"],
  ["Hellmodus","Dunkelmodus","technik"],
  ["Benachrichtigungen an","Benachrichtigungen aus","technik"],
  ["Gelesen-Haken an","Gelesen-Haken aus","technik"],
  ["Sprachnachricht","Text","technik"],
  ["Videoanruf","Telefonat","technik"],
  ["Emoji","Worte","technik"],
  ["Story","Beitrag","technik"],
  ["Funktion","Aussehen","technik"],
  ["Prototyp","fertiges Produkt","technik"],
  ["Standardlösung","Maßanfertigung","technik"],
  ["sicher","bequem","technik"],
  ["Passwörter merken","Passwort-Manager","technik"],
  ["alte Technik, die läuft","neue Technik, die zickt","technik"],
];
