/* Die Karten fuer Wavelength: Skalen mit zwei Enden, nach Themen sortiert.
   Jede Karte ist [links, rechts, Thema]. Der linke Begriff liegt am Anfang
   der Skala (Wert 0), der rechte am Ende (Wert 100).

   WICHTIG beim Ergaenzen: Eine Karte muss eine *Skala* sein, auf der man
   beliebige Dinge einordnen kann - keine blosse Gegenueberstellung.

     gut   "guter Saenger <-> schlechter Saenger"  - jeder Saenger hat dort
            einen Platz, und man kann darueber streiten.
     gut   "kalt <-> heiss", "teuer <-> billig", "ueberschaetzt <-> unterschaetzt"
     falsch "Furz <-> Ruelpser" - zwei verschiedene Dinge, dazwischen liegt
            nichts. Damit kann das Medium keinen Hinweis geben.

   Pruefung vor dem Aufnehmen: Faellt mir etwas ein, das genau in der Mitte
   liegt? Wenn nein, taugt das Paar nicht. */
const THEMEN=[
  {id:"allgemein",name:"Allgemein",emoji:"\ud83c\udfaf"},
  {id:"humor",name:"Humor & Peinlich",emoji:"\ud83d\ude2c"},
  {id:"essen",name:"Essen & Trinken",emoji:"\ud83c\udf7d\ufe0f"},
  {id:"medien",name:"Filme, Musik & Serien",emoji:"\ud83c\udfac"},
  {id:"alltag",name:"Alltag & Dinge",emoji:"\ud83c\udfe0"},
  {id:"menschen",name:"Menschen & Gefühle",emoji:"\ud83d\udc65"},
  {id:"welt",name:"Orte & Unterwegs",emoji:"\ud83c\udf0d"},
  {id:"technik",name:"Technik & Internet",emoji:"\ud83d\udcf1"}
];

const KARTEN=[

  /* --- allgemein --- */
  ["gut","schlecht","allgemein"],
  ["kalt","heiß","allgemein"],
  ["seltsam","normal","allgemein"],
  ["bunt","farblos","allgemein"],
  ["fühlt sich gut an","fühlt sich schlecht an","allgemein"],
  ["unverzichtbar","verzichtbar","allgemein"],
  ["teuer","billig","allgemein"],
  ["häufig","selten","allgemein"],
  ["berühmt","unbekannt","allgemein"],
  ["hell","dunkel","allgemein"],
  ["leise","laut","allgemein"],
  ["langsam","schnell","allgemein"],
  ["klein","groß","allgemein"],
  ["alt","neu","allgemein"],
  ["weich","hart","allgemein"],
  ["leicht","schwer","allgemein"],
  ["harmlos","gefährlich","allgemein"],
  ["hässlich","schön","allgemein"],
  ["langweilig","spannend","allgemein"],
  ["einfach","kompliziert","allgemein"],
  ["überschätzt","unterschätzt","allgemein"],
  ["nutzlos","nützlich","allgemein"],
  ["schmutzig","sauber","allgemein"],
  ["unwichtig","wichtig","allgemein"],
  ["kurzlebig","langlebig","allgemein"],
  ["zerbrechlich","unkaputtbar","allgemein"],
  ["unauffällig","auffällig","allgemein"],
  ["billig gemacht","hochwertig","allgemein"],
  ["alltäglich","besonders","allgemein"],
  ["schnell vergessen","unvergesslich","allgemein"],

  ["kurz","lang","allgemein"],
  ["dünn","dick","allgemein"],
  ["flach","tief","allgemein"],
  ["stumpf","scharf","allgemein"],
  ["trocken","nass","allgemein"],
  ["leer","voll","allgemein"],
  /* --- humor --- */
  ["guter Witz","schlechter Witz","humor"],
  ["harmloser Witz","böser Witz","humor"],
  ["Flachwitz","feiner Humor","humor"],
  ["leicht peinlich","extrem peinlich","humor"],
  ["peinlich","beeindruckend","humor"],
  ["uncool","cool","humor"],
  ["kitschig","stilvoll","humor"],
  ["aus Versehen cool","bemüht cool","humor"],
  ["harmlose Notlüge","dreiste Lüge","humor"],
  ["Missgeschick","Skandal","humor"],
  ["Kleinigkeit","große Sache","humor"],
  ["Ärgernis","Drama","humor"],
  ["Quatsch","Geniestreich","humor"],
  ["Zufallstreffer","Meisterleistung","humor"],
  ["verpönt","angesehen","humor"],
  ["albern","todernst","humor"],
  ["Aufschneider","Tiefstapler","humor"],
  ["schlechter Auftritt","großer Auftritt","humor"],
  ["niemand lacht","alle lachen","humor"],
  ["leicht daneben","komplett daneben","humor"],
  ["verzeihlich","unverzeihlich","humor"],
  ["netter Spitzname","gemeiner Spitzname","humor"],
  ["harmlose Frage","unangenehme Frage","humor"],
  ["schlechte Ausrede","gute Ausrede","humor"],
  ["kleiner Streich","gemeiner Streich","humor"],
  ["man kann drüber lachen","da lacht keiner mehr","humor"],
  ["witzig gemeint","ernst gemeint","humor"],
  ["leicht zu ertragen","kaum auszuhalten","humor"],
  ["gute Verkleidung","schlechte Verkleidung","humor"],
  ["charmant","fremdschämig","humor"],

  ["Kalauer","schwarzer Humor","humor"],
  ["Wortwitz","Slapstick","humor"],
  ["Modeunfall","perfektes Outfit","humor"],
  ["peinliches Schweigen","zu viel erzählt","humor"],
  ["Socken in Sandalen","barfuß","humor"],
  ["überschätzte Waffe","unterschätzte Waffe","humor"],
  ["sieht nicht aus wie ein Mensch","sieht aus wie ein Mensch","humor"],
  /* --- essen --- */
  ["hohes Suchtpotenzial","geringes Suchtpotenzial","essen"],
  ["Kalorienbombe","kalorienarm","essen"],
  ["geschmacksintensiv","geschmacksneutral","essen"],
  ["guter Pizzabelag","schlechter Pizzabelag","essen"],
  ["schmeckt gut","schmeckt schlecht","essen"],
  ["sauber zu essen","Sauerei beim Essen","essen"],
  ["scharf","mild","essen"],
  ["Gemüse","Obst","essen"],
  ["gute Süßigkeit","schlechte Süßigkeit","essen"],
  ["angenehme Konsistenz","unangenehme Konsistenz","essen"],
  ["herzhaft","süß","essen"],
  ["fade","würzig","essen"],
  ["Fastfood","Feinkost","essen"],
  ["gesund","ungesund","essen"],
  ["sättigt lange","sofort wieder hungrig","essen"],
  ["gutes Frühstück","schlechtes Frühstück","essen"],
  ["Alltagsessen","Festessen","essen"],
  ["riecht besser als es schmeckt","schmeckt besser als es riecht","essen"],
  ["leicht zu kochen","schwer zu kochen","essen"],
  ["gutes Partyessen","schlechtes Partyessen","essen"],
  ["kalt besser","warm besser","essen"],
  ["gutes Getränk zum Essen","schlechtes Getränk zum Essen","essen"],
  ["teilt man gern","behält man für sich","essen"],
  ["Kindergeschmack","Erwachsenengeschmack","essen"],
  ["gute Beilage","schlechte Beilage","essen"],
  ["schmeckt aufgewärmt besser","schmeckt nur frisch","essen"],
  ["gutes Eis","schlechtes Eis","essen"],
  ["billig und satt","teuer und wenig","essen"],
  ["guter Nachtisch","schlechter Nachtisch","essen"],
  ["geht zum Frühstück","nur abends","essen"],

  /* --- medien --- */
  ["guter Film","schlechter Film","medien"],
  ["guter Sänger","schlechter Sänger","medien"],
  ["die dunkle Seite","die helle Seite","medien"],
  ["guter Schauspieler","schlechter Schauspieler","medien"],
  ["gute Musik","schlechte Musik","medien"],
  ["überschätzter Musiker","unterschätzter Musiker","medien"],
  ["gute Serie","schlechte Serie","medien"],
  ["überschätztes Buch","unterschätztes Buch","medien"],
  ["guter Disney-Charakter","böser Disney-Charakter","medien"],
  ["Film war besser","Buch war besser","medien"],
  ["Blockbuster","Arthouse","medien"],
  ["seicht","tiefgründig","medien"],
  ["Kinderfilm","Erwachsenenfilm","medien"],
  ["Komödie","Drama","medien"],
  ["Ohrwurm","Kunstwerk","medien"],
  ["Partymusik","Musik zum Zuhören","medien"],
  ["Radiohit","Geheimtipp","medien"],
  ["guter Schurke","langweiliger Schurke","medien"],
  ["Held","Antiheld","medien"],
  ["zum Weinen","zum Lachen","medien"],
  ["einmal schauen","immer wieder schauen","medien"],
  ["gutes Ende","schlechtes Ende","medien"],
  ["guter Soundtrack","schlechter Soundtrack","medien"],
  ["gut gealtert","schlecht gealtert","medien"],
  ["gute Fortsetzung","schlechte Fortsetzung","medien"],
  ["guter Filmtitel","schlechter Filmtitel","medien"],
  ["gute Tanzmusik","schlechte Tanzmusik","medien"],
  ["harmloser Horror","echter Horror","medien"],
  ["gutes Videospiel","schlechtes Videospiel","medien"],
  ["guter Podcast","schlechter Podcast","medien"],

  /* --- alltag --- */
  ["praktisch","hübsch","alltag"],
  ["altmodisch","modern","alltag"],
  ["schlicht","protzig","alltag"],
  ["günstig","luxuriös","alltag"],
  ["unbequem","bequem","alltag"],
  ["Wegwerfartikel","Erbstück","alltag"],
  ["Massenware","Handarbeit","alltag"],
  ["Gebrauchsgegenstand","Deko","alltag"],
  ["Werkzeug","Spielzeug","alltag"],
  ["aufgeräumt","gemütlich","alltag"],
  ["gute Wohngegend","schlechte Wohngegend","alltag"],
  ["lohnt die Reparatur","gleich wegwerfen","alltag"],
  ["gutes Geschenk","schlechtes Geschenk","alltag"],
  ["gut angelegtes Geld","Geldverschwendung","alltag"],
  ["lästige Hausarbeit","angenehme Hausarbeit","alltag"],
  ["schnell erledigt","zieht sich ewig","alltag"],
  ["gutes Möbelstück","schlechtes Möbelstück","alltag"],
  ["braucht man täglich","braucht man nie","alltag"],
  ["leicht sauber zu halten","schwer sauber zu halten","alltag"],
  ["guter Morgen","schlechter Morgen","alltag"],
  ["entspannt","stressig","alltag"],
  ["Pflicht","Vergnügen","alltag"],
  ["Routine","Abenteuer","alltag"],
  ["gutes Wetter","schlechtes Wetter","alltag"],
  ["gute Jahreszeit","schlechte Jahreszeit","alltag"],
  ["guter Wochentag","schlechter Wochentag","alltag"],
  ["laute Nachbarn","leise Nachbarn","alltag"],
  ["gut organisiert","völlig chaotisch","alltag"],
  ["kurze Besorgung","ganzer Tag","alltag"],
  ["sinnvolle Anschaffung","Staubfänger","alltag"],

  /* --- menschen --- */
  ["schüchtern","selbstbewusst","menschen"],
  ["streng","nachsichtig","menschen"],
  ["sparsam","großzügig","menschen"],
  ["pessimistisch","optimistisch","menschen"],
  ["chaotisch","ordentlich","menschen"],
  ["spontan","geplant","menschen"],
  ["stur","nachgiebig","menschen"],
  ["faul","fleißig","menschen"],
  ["unhöflich","höflich","menschen"],
  ["ernst","verspielt","menschen"],
  ["Kopfmensch","Bauchmensch","menschen"],
  ["Realist","Träumer","menschen"],
  ["Zuhörer","Redner","menschen"],
  ["gute Eigenschaft","schlechte Eigenschaft","menschen"],
  ["guter Freund","schlechter Freund","menschen"],
  ["guter Chef","schlechter Chef","menschen"],
  ["gute Nachricht","schlechte Nachricht","menschen"],
  ["ehrliches Kompliment","plumpes Kompliment","menschen"],
  ["harmlose Kritik","harte Kritik","menschen"],
  ["gute Entschuldigung","schlechte Entschuldigung","menschen"],
  ["vertrauenswürdig","unzuverlässig","menschen"],
  ["anstrengend","angenehm","menschen"],
  ["leicht beleidigt","nimmt alles gelassen","menschen"],
  ["guter Ratschlag","schlechter Ratschlag","menschen"],
  ["kleine Geste","große Geste","menschen"],
  ["Smalltalk","tiefes Gespräch","menschen"],
  ["gute Angewohnheit","schlechte Angewohnheit","menschen"],
  ["gutes Vorbild","schlechtes Vorbild","menschen"],
  ["Angst","Respekt","menschen"],
  ["Nervosität","Vorfreude","menschen"],

  /* --- welt --- */
  ["gutes Reiseziel","schlechtes Reiseziel","welt"],
  ["Berge","Meer","welt"],
  ["Stadt","Land","welt"],
  ["nah","weit weg","welt"],
  ["Sehenswürdigkeit","Geheimtipp","welt"],
  ["Zelt","Hotel","welt"],
  ["gute Unterkunft","schlechte Unterkunft","welt"],
  ["entspannter Urlaub","anstrengender Urlaub","welt"],
  ["Norden","Süden","welt"],
  ["warmes Land","kaltes Land","welt"],
  ["guter Strand","schlechter Strand","welt"],
  ["touristisch","unberührt","welt"],
  ["gute Aussicht","schlechte Aussicht","welt"],
  ["gutes Verkehrsmittel","schlechtes Verkehrsmittel","welt"],
  ["Fahrrad","Auto","welt"],
  ["schnell","sparsam","welt"],
  ["Elektro","Benzin","welt"],
  ["kurze Strecke","lange Strecke","welt"],
  ["angenehme Reise","reinste Strapaze","welt"],
  ["gutes Auto","schlechtes Auto","welt"],
  ["sicherer Ort","gefährlicher Ort","welt"],
  ["lohnt den Umweg","nicht der Rede wert","welt"],
  ["gut zu Fuß","nur mit Fahrzeug","welt"],
  ["belebt","menschenleer","welt"],
  ["gutes Souvenir","sinnloses Mitbringsel","welt"],
  ["viel zu früh am Flughafen","auf den letzten Drücker","welt"],

  /* --- technik --- */
  ["analog","digital","technik"],
  ["gute App","schlechte App","technik"],
  ["gutes Passwort","schlechtes Passwort","technik"],
  ["sicher","bequem","technik"],
  ["intuitiv","erklärungsbedürftig","technik"],
  ["gutes Gerät","schlechtes Gerät","technik"],
  ["hält ewig","geht sofort kaputt","technik"],
  ["gute Webseite","schlechte Webseite","technik"],
  ["nützliche Benachrichtigung","nervige Benachrichtigung","technik"],
  ["Werbung","Inhalt","technik"],
  ["reißerisch","sachlich","technik"],
  ["gutes Video","schlechtes Video","technik"],
  ["Zeitverschwendung","gut investierte Zeit","technik"],
  ["leicht zu reparieren","Wegwerfgerät","technik"],
  ["guter Kundendienst","schlechter Kundendienst","technik"],
  ["kostenlos","Abo","technik"],
  ["alte Technik, die läuft","neue Technik, die zickt","technik"],
  ["überschätzte Funktion","unterschätzte Funktion","technik"],
  ["offline","ständig online","technik"],
  ["Fernsehen","Streaming","technik"],
  ["Radio","Podcast","technik"],
  ["kurzer Clip","langes Video","technik"],
  ["gute Erfindung","schlechte Erfindung","technik"],
  ["braucht kein Mensch","heute unverzichtbar","technik"],
  ["leicht zu merken","ständig vergessen","technik"],
  ["guter Nutzername","peinlicher Nutzername","technik"],
];
