/* Die Fragenpaare des Spiels.
   Jeder Eintrag: [Frage A, Frage B, Kategorie].
   Die beiden Fragen eines Paares koennen zu aehnlichen Antworten fuehren –
   muessen aber nicht. Keine Frage und kein Paar kommt doppelt vor.
   Der Host waehlt die Kategorien und zieht daraus ohne Zuruecklegen (ziehePaar in host.js). */
const KATEGORIEN=[
  {id:"zahlen",name:"Zahlen & Mengen",emoji:"🔢"},
  {id:"alltag",name:"Alltag & Routine",emoji:"🏠"},
  {id:"essen",name:"Essen & Trinken",emoji:"🍽️"},
  {id:"orte",name:"Orte & Reisen",emoji:"🌍"},
  {id:"menschen",name:"Menschen",emoji:"👥"},
  {id:"ich",name:"Über dich",emoji:"🙂"},
  {id:"dinge",name:"Dinge & Geld",emoji:"💶"},
  {id:"arbeit",name:"Arbeit & Schule",emoji:"💼"},
  {id:"medien",name:"Internet & Apps",emoji:"📱"},
  {id:"feste",name:"Feste & Jahreszeiten",emoji:"🎉"},
  {id:"sport",name:"Sport",emoji:"⚽"},
  {id:"musik",name:"Musik",emoji:"🎵"},
  {id:"filme",name:"Filme & Serien",emoji:"🎬"},
  {id:"games",name:"Games",emoji:"🎮"},
  {id:"tiere",name:"Tiere",emoji:"🐾"},
  {id:"autos",name:"Autos & Fahren",emoji:"🚗"},
  {id:"kultur",name:"Kultur & Wissen",emoji:"📚"}
];

const PAIRS=[
  ["Wie viele Stunden hast du letzte Nacht geschlafen?","Wie viele Stunden warst du gestern am Handy?","zahlen"],
  ["Wie viel Geld gibst du pro Woche für Essen aus?","Wie viel kostet dein Handyvertrag im Monat?","zahlen"],
  ["Wie oft machst du pro Woche Sport?","Wie oft bestellst du pro Woche Essen?","zahlen"],
  ["Wie viele Menschen wohnen in deinem Haushalt?","Wie viele richtig enge Freunde hast du?","zahlen"],
  ["Wie viele Paar Schuhe besitzt du?","Wie viele Jacken hängen bei dir im Flur?","zahlen"],
  ["Wie viele Kilometer fährst du am Tag?","Wie viele Kilometer gehst du am Tag zu Fuß?","zahlen"],
  ["Wie viel Prozent Akku hat dein Handy gerade?","Wie viel Prozent deines Geldes sparst du?","zahlen"],
  ["Wie alt warst du bei deinem ersten Kuss?","Wie alt warst du, als du zum ersten Mal allein verreist bist?","zahlen"],
  ["Wie viele Stunden am Tag schaust du auf dein Handy?","Wie viele Stunden am Tag arbeitest du wirklich konzentriert?","zahlen"],
  ["Wie viele Geschwister hast du?","Wie viele Haustiere hattest du in deinem Leben?","zahlen"],
  ["Wie viele Sprachen sprichst du?","Wie viele Länder hast du bereist?","zahlen"],
  ["Wie viele Gläser Wasser trinkst du am Tag?","Wie viele Mahlzeiten isst du am Tag?","zahlen"],
  ["Wie oft im Jahr gehst du zum Friseur?","Wie oft im Jahr gehst du zum Arzt?","zahlen"],
  ["Wie viele Passwörter hast du im Kopf?","Wie viele Telefonnummern kennst du auswendig?","zahlen"],
  ["Wie viele Wecker stellst du dir?","Wie oft drückst du morgens die Schlummertaste?","zahlen"],
  ["Wie viele Fotos machst du im Urlaub an einem Tag?","Wie viele Fotos auf deinem Handy siehst du nie wieder an?","zahlen"],
  ["Wie viele Bücher liest du im Jahr?","Wie viele Filme schaust du im Monat?","zahlen"],
  ["Wie viele Tage im Jahr bist du krank?","Wie viele Tage Urlaub nimmst du am Stück?","zahlen"],
  ["Wie viele Nachbarn kennst du mit Namen?","Wie viele Nachbarn grüßt du?","zahlen"],
  ["Wie viele Paar Socken besitzt du?","Wie viele T-Shirts hast du im Schrank?","zahlen"],
  ["Wie viel Trinkgeld gibst du im Restaurant?","Wie viel darf ein Kaffee für dich kosten?","zahlen"],
  ["Wie viele Tabs hast du gerade offen?","Wie viele Apps laufen bei dir im Hintergrund?","zahlen"],
  ["Wie alt ist dein Handy?","Wie alt ist dein Auto?","zahlen"],
  ["Wie viele Kilometer läufst du in der Woche?","Wie viele Kilometer fährst du in der Woche Rad?","zahlen"],
  ["Wie viele Kissen liegen auf deinem Bett?","Wie viele Decken hast du zuhause?","zahlen"],
  ["Wie viele Menschen könntest du jetzt spontan anrufen?","Wie viele Menschen kennen deine Adresse?","zahlen"],
  ["Wie viele Minuten brauchst du zum Einschlafen?","Wie lange bleibst du nach dem Wecker noch liegen?","zahlen"],
  ["Wie viele ungelesene Mails hast du?","Wie viele ungelesene Nachrichten hast du?","zahlen"],
  ["Wie viel würdest du für gute Schuhe ausgeben?","Was hat dein teuerstes Kleidungsstück gekostet?","zahlen"],
  ["Wie viele Stunden Schlaf brauchst du wirklich?","Wie lange schläfst du am Wochenende?","zahlen"],
  ["Wie schnell fährst du auf der Autobahn?","Wie schnell fährst du innerorts wirklich?","zahlen"],
  ["Wie warm ist es bei dir in der Wohnung?","Ab wie viel Grad machst du die Heizung an?","zahlen"],
  ["Wie viele Tassen stehen in deinem Schrank?","Wie viele Teller braucht ihr wirklich?","zahlen"],
  ["Wie viele Kabel liegen ungenutzt bei dir herum?","Wie viele Ladegeräte besitzt du?","zahlen"],
  ["Wie viele Stunden sitzt du am Tag?","Wie viele Stunden bist du am Tag draußen?","zahlen"],
  ["Wie oft im Monat gehst du essen?","Wie oft im Monat kochst du richtig aufwendig?","zahlen"],
  ["Wie viele Umzüge hattest du schon?","Wie viele Adressen hattest du in deinem Leben?","zahlen"],
  ["Wie viele Leute waren auf deiner letzten Feier?","Wie viele Leute würdest du zu deiner Hochzeit einladen?","zahlen"],
  ["Wie viele Serien schaust du parallel?","Wie viele Bücher liegen bei dir angefangen herum?","zahlen"],
  ["Wie viele Kilometer ist deine Heimatstadt entfernt?","Wie weit ist deine Arbeit weg?","zahlen"],
  ["Wie viele Minuten stehst du unter der Dusche?","Wie viele Minuten brauchst du zum Anziehen?","zahlen"],
  ["Wie viele Kilo hast du im letzten Jahr zugenommen?","Wie viele Kilo würdest du gern abnehmen?","zahlen"],
  ["Wie viele Sekunden hältst du die Luft an?","Wie lange kannst du auf einem Bein stehen?","zahlen"],
  ["Wie viel gibst du im Monat für Abos aus?","Wie viel zahlst du im Monat für dein Handy?","zahlen"],
  ["Wie viele Termine hast du diese Woche?","Wie viele davon würdest du gern absagen?","zahlen"],
  ["Wie viele Kilometer bist du am Stück gelaufen?","Wie viele Kilometer bist du am Stück Rad gefahren?","zahlen"],
  ["Wie viele Pflanzen stehen bei dir zuhause?","Wie viele davon leben noch?","zahlen"],
  ["Wie viele Flaschen stehen in deinem Pfandkorb?","Wie viele Mülltüten bringst du pro Woche raus?","zahlen"],
  ["Wie viele Stunden am Stück warst du schon wach?","Wie viele Stunden am Stück hast du schon geschlafen?","zahlen"],
  ["Wie viele Alarme sind auf deinem Handy gespeichert?","Wie viele Erinnerungen hast du dir gesetzt?","zahlen"],
  ["Wie oft wechselst du die Bettwäsche?","Wie oft saugst du?","alltag"],
  ["Wann gehst du normalerweise ins Bett?","Wann stehst du am Wochenende auf?","alltag"],
  ["Wie lange brauchst du morgens im Bad?","Wie lange brauchst du zur Arbeit?","alltag"],
  ["Wie lange hältst du es ohne Handy aus?","Wie lange hältst du es aus, ohne zu reden?","alltag"],
  ["Wann isst du zu Abend?","Wann machst du Feierabend?","alltag"],
  ["Wann fängt für dich das Wochenende an?","Wann fängt für dich der Abend an?","alltag"],
  ["Wann schaust du morgens zum ersten Mal aufs Handy?","Wann trinkst du deinen ersten Kaffee?","alltag"],
  ["Wie lange bleibst du auf einer Party?","Wie lange hältst du es bei einer Familienfeier aus?","alltag"],
  ["Wie lange dauert bei dir ein Telefonat?","Wie lange dauert bei dir ein Einkauf?","alltag"],
  ["Was machst du als Erstes nach dem Aufstehen?","Was machst du als Letztes vor dem Schlafen?","alltag"],
  ["Welche Hausarbeit machst du am liebsten?","Welche Hausarbeit schiebst du ewig auf?","alltag"],
  ["Was räumst du zuerst auf, wenn Besuch kommt?","Was versteckst du, wenn Besuch kommt?","alltag"],
  ["Welches Körperteil tut dir gerade weh?","Welches Körperteil magst du an dir am liebsten?","alltag"],
  ["Was tust du für deine Gesundheit?","Was solltest du dringend öfter machen?","alltag"],
  ["In welchem Raum verbringst du die meiste Zeit?","Welcher Raum ist bei dir am unordentlichsten?","alltag"],
  ["Was steht auf deiner Fensterbank?","Welche Pflanze hast du zuletzt eingehen lassen?","alltag"],
  ["Womit fängt dein Morgen wirklich an?","Was gehört für dich zu einem guten Abend?","alltag"],
  ["Wie kommst du zur Arbeit?","Wie kommst du abends nach Hause?","alltag"],
  ["Was hörst du beim Aufräumen?","Was läuft bei dir nebenbei, wenn du kochst?","alltag"],
  ["Wann kaufst du am liebsten ein?","Wann ist dein Supermarkt am vollsten?","alltag"],
  ["Was steht bei dir immer auf dem Einkaufszettel ganz oben?","Was vergisst du beim Einkaufen ständig?","alltag"],
  ["Wo liegen bei dir die Schlüssel?","Wo landet bei dir die Post?","alltag"],
  ["Was ist bei dir der größte Zeitfresser?","Was machst du, obwohl du eigentlich keine Zeit dafür hast?","alltag"],
  ["Wie oft räumst du deinen Schreibtisch auf?","Wie oft machst du dein Handy leer?","alltag"],
  ["Was machst du, wenn du nicht einschlafen kannst?","Was machst du, wenn du nachts aufwachst?","alltag"],
  ["Was ziehst du zuhause an?","Was trägst du, wenn niemand vorbeikommt?","alltag"],
  ["Wann duschst du normalerweise?","Wann wäschst du dir die Haare?","alltag"],
  ["Was trinkst du direkt nach dem Aufstehen?","Was ist dein erstes Essen am Tag?","alltag"],
  ["Wie oft wäschst du Wäsche?","Wie oft bügelst du?","alltag"],
  ["Welche Schublade ist bei dir das reinste Chaos?","Was findet man in deiner Kramkiste?","alltag"],
  ["Was machst du in der Mittagspause?","Was machst du in der ersten freien Stunde am Tag?","alltag"],
  ["Womit belohnst du dich nach einem harten Tag?","Was machst du, wenn du gestresst bist?","alltag"],
  ["Was nervt dich morgens am meisten?","Was bringt deinen Tag sofort durcheinander?","alltag"],
  ["Wie oft kontrollierst du dein Konto?","Wie oft schaust du auf die Uhr?","alltag"],
  ["Was hast du heute schon erledigt?","Was steht heute noch auf deiner Liste?","alltag"],
  ["Was ist dein Wochenend-Ritual?","Was gehört für dich zu einem perfekten Sonntag?","alltag"],
  ["Wie machst du dein Bett?","Wie sieht dein Kleiderschrank innen aus?","alltag"],
  ["Was liegt in deinem Bad ganz vorne?","Was benutzt du im Bad täglich?","alltag"],
  ["Wie lange bleibst du morgens noch liegen?","Wie lange sitzt du abends noch auf dem Sofa?","alltag"],
  ["Was machst du, während du auf den Bus wartest?","Was machst du, wenn dein Handy gleich leer ist?","alltag"],
  ["Wie oft schaust du in den Kühlschrank, ohne Hunger zu haben?","Wie oft öffnest du dieselbe App hintereinander?","alltag"],
  ["Was hast du heute zuletzt weggeworfen?","Was hast du heute zuletzt gekauft?","alltag"],
  ["Wie oft lüftest du am Tag?","Wie oft machst du das Licht an, obwohl es hell ist?","alltag"],
  ["Wie planst du deine Woche?","Wo schreibst du dir Termine auf?","alltag"],
  ["Was machst du, wenn dein Zug Verspätung hat?","Was machst du, wenn du irgendwo zu früh bist?","alltag"],
  ["Womit hältst du dich abends wach?","Was hilft dir, morgens wach zu werden?","alltag"],
  ["Was hast du zuletzt aufgeschoben und dann doch gemacht?","Was liegt seit Wochen unerledigt herum?","alltag"],
  ["Wie oft gehst du spazieren?","Wie oft bist du einfach mal ohne Ziel unterwegs?","alltag"],
  ["Was machst du, wenn du allein zuhause bist?","Was machst du, wenn du eine Stunde frei hast?","alltag"],
  ["Welchen Wochentag magst du am liebsten?","Welcher Tag ist bei dir am vollsten?","alltag"],
  ["Was ist dein Lieblingsgetränk?","Was trinkst du, wenn du krank bist?","essen"],
  ["Was isst du am liebsten zum Frühstück?","Was isst du nachts, wenn du Hunger bekommst?","essen"],
  ["Nenne etwas, das immer in deinem Kühlschrank ist.","Nenne etwas, das du nie kaufen würdest.","essen"],
  ["Was bestellst du an der Bar?","Was trinkst du, wenn du am nächsten Tag früh raus musst?","essen"],
  ["Welche Pizza bestellst du?","Welchen Belag magst du überhaupt nicht?","essen"],
  ["Was kochst du, wenn Besuch kommt?","Was kochst du, wenn du keine Lust hast?","essen"],
  ["Was isst du, wenn du traurig bist?","Was isst du zur Belohnung?","essen"],
  ["Welches Gemüse magst du nicht?","Was hast du als Kind nie gegessen?","essen"],
  ["Was steht auf deinem Einkaufszettel immer drauf?","Was kaufst du immer, obwohl du es nicht brauchst?","essen"],
  ["Wie trinkst du deinen Kaffee?","Was bestellst du im Café?","essen"],
  ["Was kocht deine Familie am besten?","Welches Gericht kannst du am besten kochen?","essen"],
  ["Welches Fast Food geht immer?","Was isst du nach einer langen Nacht?","essen"],
  ["Welche Süßigkeit könntest du nie aufgeben?","Was liegt bei dir immer im Vorratsschrank?","essen"],
  ["Was trinkst du zum Anstoßen?","Was trinkst du an Silvester?","essen"],
  ["Was ist in deinem Kühlschrank abgelaufen?","Was findet man ganz hinten in deinem Schrank?","essen"],
  ["Welches Gericht bestellst du im Restaurant fast immer?","Was probierst du nie, obwohl es auf der Karte steht?","essen"],
  ["Was isst du zum Mittag, wenn es schnell gehen muss?","Was gibt es bei dir, wenn der Kühlschrank leer ist?","essen"],
  ["Welche Soße darf nicht fehlen?","Welches Gewürz benutzt du am meisten?","essen"],
  ["Was ist dein Lieblingsbrot?","Was kommt bei dir aufs Butterbrot?","essen"],
  ["Welchen Käse magst du am liebsten?","Welchen Käse würdest du nie essen?","essen"],
  ["Was isst du beim Grillen zuerst?","Was bringst du zum Grillen immer mit?","essen"],
  ["Welche Suppe magst du?","Was isst du, wenn dir kalt ist?","essen"],
  ["Was ist dein Lieblingsobst?","Welches Obst kaufst du nie?","essen"],
  ["Wie magst du deine Eier?","Was isst du am Sonntagmorgen?","essen"],
  ["Welchen Kuchen backst du?","Welchen Kuchen isst du am liebsten?","essen"],
  ["Was ist dein Lieblingseis?","Welche Eissorte findest du überbewertet?","essen"],
  ["Was isst du im Kino?","Was knabberst du beim Serienabend?","essen"],
  ["Was trinkst du beim Sport?","Was trinkst du nach dem Sport?","essen"],
  ["Welches Nationalgericht magst du am liebsten?","Welche Küche bestellst du am häufigsten?","essen"],
  ["Was ist das Schärfste, was du gegessen hast?","Wie scharf darf dein Essen sein?","essen"],
  ["Was ist dein Lieblingsfrühstück im Urlaub?","Was fehlt dir im Ausland beim Essen?","essen"],
  ["Welche Chipssorte nimmst du?","Was ist dein liebster Snack am Abend?","essen"],
  ["Was ist das Seltsamste, was du je gegessen hast?","Was würdest du niemals probieren?","essen"],
  ["Welches Getränk trinkst du am meisten?","Was steht bei dir immer im Kühlschrank zum Trinken?","essen"],
  ["Was kommt bei dir in den Tee?","Welchen Tee trinkst du abends?","essen"],
  ["Was ist dein Lieblingsrestaurant?","Wo isst du am häufigsten auswärts?","essen"],
  ["Was bestellst du beim Bäcker?","Was holst du dir auf dem Weg zur Arbeit?","essen"],
  ["Was ist dein liebstes Resteessen?","Was wirfst du am häufigsten weg?","essen"],
  ["Welche Nudelform nimmst du?","Welche Nudelsoße kochst du am häufigsten?","essen"],
  ["Was gehört für dich in einen guten Salat?","Welches Dressing nimmst du?","essen"],
  ["Was isst du beim Autofahren?","Was nimmst du dir für lange Fahrten mit?","essen"],
  ["Welches Essen erinnert dich an deine Kindheit?","Was hat deine Oma am besten gekocht?","essen"],
  ["Was bestellst du beim Asiaten?","Was bestellst du beim Italiener?","essen"],
  ["Was isst du zum Geburtstag?","Was gibt es bei euch zu Ostern?","essen"],
  ["Welches Küchengerät nutzt du am meisten?","Welches Küchengerät steht ungenutzt herum?","essen"],
  ["Wie viele Tassen Tee trinkst du am Tag?","Wie viele Tassen Kaffee brauchst du morgens?","essen"],
  ["Was ist deine liebste Beilage?","Was isst du am häufigsten als Beilage?","essen"],
  ["Was hast du zuletzt versalzen?","Was ist dir beim Kochen zuletzt misslungen?","essen"],
  ["Was ist dein Lieblingsfrühstücksmüsli?","Was schüttest du auf deine Cornflakes?","essen"],
  ["Was nimmst du mit zum Picknick?","Was gehört in eine gute Brotdose?","essen"],
  ["Was ist dein Lieblings-Urlaubsland?","In welchem Land würdest du nie leben wollen?","orte"],
  ["Nenne eine Stadt, die du liebst.","Nenne eine Stadt, die überbewertet ist.","orte"],
  ["Wo war dein letzter Urlaub?","Wo möchtest du unbedingt mal hin?","orte"],
  ["Was ist dein Lieblingsplatz zuhause?","Wo im Haus bist du am seltensten?","orte"],
  ["Wohin gehst du, wenn du Ruhe brauchst?","Wohin gehst du, wenn du Trubel brauchst?","orte"],
  ["Welches Bundesland kennst du am besten?","In welchem Bundesland warst du noch nie?","orte"],
  ["Nenne ein Land, dessen Essen du liebst.","Nenne ein Land, in das du auswandern würdest.","orte"],
  ["Wo kaufst du meistens ein?","Welchen Laden betrittst du nie?","orte"],
  ["Welcher Ort erinnert dich an deine Kindheit?","Wo warst du das letzte Mal richtig glücklich?","orte"],
  ["Welche Stadt möchtest du noch einmal besuchen?","In welcher Stadt warst du am längsten?","orte"],
  ["Wie kommst du am liebsten in den Urlaub?","Welches Verkehrsmittel meidest du?","orte"],
  ["Was packst du immer zuletzt ein?","Was vergisst du beim Packen immer?","orte"],
  ["Woran erinnerst du dich vom letzten Urlaub zuerst?","Was war dein schönster Urlaubsmoment?","orte"],
  ["Berge oder Meer?","Stadt oder Land?","orte"],
  ["Was ist dein liebstes Reiseziel in Deutschland?","Wo würdest du ein Wochenende verbringen?","orte"],
  ["Welche Insel würdest du gern sehen?","Auf welcher Insel warst du schon?","orte"],
  ["Was machst du am ersten Urlaubstag?","Was machst du am letzten Abend im Urlaub?","orte"],
  ["Wo übernachtest du im Urlaub am liebsten?","Wo hast du zuletzt übernachtet?","orte"],
  ["Was ist das Schönste, was du je gesehen hast?","Welcher berühmte Ort war eine Enttäuschung?","orte"],
  ["Welches Café ist dein Stammlokal?","Wo triffst du dich mit Freunden?","orte"],
  ["Was gefällt dir an deiner Stadt am besten?","Was würdest du in deiner Stadt sofort ändern?","orte"],
  ["Wo möchtest du im Alter leben?","Wo würdest du niemals wohnen wollen?","orte"],
  ["Wie lange dauerte dein längster Flug?","Wie lange war deine längste Reise?","orte"],
  ["Was machst du im Flugzeug?","Was machst du direkt nach der Landung?","orte"],
  ["Was ist dein liebstes Urlaubssouvenir?","Was bringst du von Reisen immer mit?","orte"],
  ["Welche Sprache würdest du gern für eine Reise lernen?","In welchem Land hattest du Verständigungsprobleme?","orte"],
  ["Was war deine schlimmste Unterkunft?","Was war dein schönstes Hotelzimmer?","orte"],
  ["Wohin würdest du morgen spontan fahren?","Wohin würdest du fahren, um jemanden zu überraschen?","orte"],
  ["Welcher Bahnhof nervt dich am meisten?","Welcher Flughafen ist dein liebster?","orte"],
  ["Was war dein erster Urlaub ohne Eltern?","Wo warst du als Kind immer im Urlaub?","orte"],
  ["Was machst du an einem Urlaubstag am liebsten?","Was machst du im Urlaub garantiert nicht?","orte"],
  ["Welchen See kennst du am besten?","An welchem Fluss warst du zuletzt?","orte"],
  ["Wo stehst du gern in der Natur?","Welcher Park ist dein liebster?","orte"],
  ["Welches Museum hat dich beeindruckt?","Welche Sehenswürdigkeit fandest du enttäuschend?","orte"],
  ["Was ist dein liebstes Land in Europa?","Welches europäische Land kennst du gar nicht?","orte"],
  ["Wie weit war dein weitester Urlaub entfernt?","Wie weit warst du je von zuhause weg?","orte"],
  ["Was war deine ungewöhnlichste Unterkunft?","Wo würdest du nie übernachten?","orte"],
  ["Was ist dein liebstes Reisegepäck?","Was nimmst du als Handgepäck mit?","orte"],
  ["Wann fängst du an, eine Reise zu planen?","Wann buchst du deinen Urlaub?","orte"],
  ["Wo isst du im Urlaub am liebsten?","Wo würdest du im Urlaub nie essen?","orte"],
  ["Welcher Ort ist deine zweite Heimat?","Wo fühlst du dich sofort wohl?","orte"],
  ["Was hast du auf einer Reise verloren?","Was ist dir im Urlaub Peinliches passiert?","orte"],
  ["Welche Stadt hat die schönste Altstadt?","In welcher Stadt würdest du gern arbeiten?","orte"],
  ["Was machst du bei Regen im Urlaub?","Was rettet einen verregneten Urlaubstag?","orte"],
  ["Welches Land hat die freundlichsten Menschen?","Wo hast du dich am fremdesten gefühlt?","orte"],
  ["Wohin würdest du deine Eltern einladen?","Wohin würdest du mit deinen Freunden fahren?","orte"],
  ["Was war deine teuerste Reise?","Was war dein günstigster Urlaub?","orte"],
  ["Welchen Ort willst du unbedingt nochmal sehen?","Welchen Ort meidest du seit Jahren?","orte"],
  ["Was machst du bei einer langen Zugfahrt?","Was hörst du unterwegs?","orte"],
  ["Wo warst du zuletzt spazieren?","Wo würdest du nachts nicht allein langgehen?","orte"],
  ["Wen rufst du an, wenn etwas Gutes passiert ist?","Wer weiß am meisten über dich?","menschen"],
  ["Wer in deiner Familie ist dir am ähnlichsten?","Wer hat dich am meisten geprägt?","menschen"],
  ["Wen aus deiner Schulzeit würdest du gern wiedersehen?","Wen aus deiner Schulzeit hast du völlig vergessen?","menschen"],
  ["Wer kocht bei euch zuhause?","Wer räumt bei euch die Spülmaschine aus?","menschen"],
  ["Mit wem schreibst du am meisten?","Wen siehst du am seltensten, obwohl du ihn magst?","menschen"],
  ["Wer war dein erstes Vorbild?","Wen hast du als Kind bewundert?","menschen"],
  ["Nenne einen Promi, den du treffen möchtest.","Nenne einen Promi, den du nicht ausstehen kannst.","menschen"],
  ["Mit welcher berühmten Person würdest du essen gehen?","Wen aus der Geschichte würdest du gern treffen?","menschen"],
  ["Welchen Lehrer hast du nie vergessen?","Wer hat dir am meisten beigebracht?","menschen"],
  ["Was war dein erster Spitzname?","Wie nennt dich deine Familie?","menschen"],
  ["Wer bringt dich am schnellsten zum Lachen?","Wer nervt dich am schnellsten?","menschen"],
  ["Wen würdest du um Geld bitten?","Wem würdest du sofort Geld leihen?","menschen"],
  ["Wer ist bei euch immer zu spät?","Wer ist immer als Erster da?","menschen"],
  ["Wem vertraust du blind?","Wem würdest du dein Handy ungesperrt geben?","menschen"],
  ["Wer hat den schrägsten Humor in deinem Umfeld?","Über wessen Witze lachst du immer?","menschen"],
  ["Wen aus deiner Familie würdest du auf eine Insel mitnehmen?","Mit wem könntest du eine Woche allein verbringen?","menschen"],
  ["Wer war deine erste große Liebe?","An wen denkst du manchmal noch?","menschen"],
  ["Wer ist dein ältester Freund?","Wen kennst du erst kurz, magst ihn aber sofort?","menschen"],
  ["Wen hast du zuletzt angerufen?","Wem hast du zuletzt geschrieben?","menschen"],
  ["Wer gibt dir die besten Ratschläge?","Wessen Rat solltest du öfter ignorieren?","menschen"],
  ["Wer kann am besten kochen, den du kennst?","Bei wem isst du am liebsten?","menschen"],
  ["Wer in deinem Umfeld ist am ordentlichsten?","Wer ist das größte Chaos?","menschen"],
  ["Wen würdest du gern mal überraschen?","Wem schuldest du noch einen Besuch?","menschen"],
  ["Wer hat dich zuletzt zum Weinen gebracht?","Wer hat dich zuletzt richtig glücklich gemacht?","menschen"],
  ["Wer redet in deinem Umfeld am meisten?","Wer hört am besten zu?","menschen"],
  ["Wen bewunderst du für seinen Mut?","Wer hat dich zu etwas überredet, das du nie gemacht hättest?","menschen"],
  ["Wer war dein bester Schulfreund?","Mit wem hast du am meisten Blödsinn gemacht?","menschen"],
  ["Wer aus deiner Familie erzählt die besten Geschichten?","Wer wiederholt immer dieselbe Geschichte?","menschen"],
  ["Wen würdest du zu deinem Nachbarn machen?","Mit wem könntest du niemals zusammenwohnen?","menschen"],
  ["Wer schenkt dir immer das Richtige?","Wem fällt es schwer, dich zu beschenken?","menschen"],
  ["Wer hat den größten Freundeskreis?","Wer kennt in deiner Runde alle?","menschen"],
  ["Wen fragst du, wenn dein Handy kaputt ist?","Wen rufst du bei Computerproblemen an?","menschen"],
  ["Wer bringt dich dazu, Sport zu machen?","Wer verabredet sich mit dir am zuverlässigsten?","menschen"],
  ["Wer hat den besten Musikgeschmack?","Wessen Playlist würdest du übernehmen?","menschen"],
  ["Wer streitet in deiner Familie am meisten?","Wer schlichtet bei euch?","menschen"],
  ["Wem hast du zuletzt geholfen?","Wer schuldet dir noch einen Gefallen?","menschen"],
  ["Wer war dein erster Chef?","Mit welchem Kollegen verstehst du dich am besten?","menschen"],
  ["Wen würdest du gern einen Tag lang sein?","In wessen Leben würdest du gern hineinschauen?","menschen"],
  ["Wer hat dir das Fahrradfahren beigebracht?","Wer hat dir das Kochen beigebracht?","menschen"],
  ["Wen vermisst du gerade?","Wer taucht bei euch immer unangekündigt auf?","menschen"],
  ["Wer hat den besten Kleidungsstil in deinem Umfeld?","Von wem würdest du dich gern beraten lassen?","menschen"],
  ["Wer erzählt am liebsten von früher?","Wer lebt am meisten im Hier und Jetzt?","menschen"],
  ["Wen würdest du bei einer Prüfung abschreiben lassen?","Wer war in der Schule der Streber?","menschen"],
  ["Mit wem würdest du gern eine Weltreise machen?","Wer wäre der schlechteste Reisebegleiter?","menschen"],
  ["Wer ist der Sturste, den du kennst?","Wer gibt am schnellsten nach?","menschen"],
  ["Wen erkennst du am Lachen?","Wessen Lachen ist am ansteckendsten?","menschen"],
  ["Wer hat dir den besten Rat gegeben?","Welchen Rat hast du nie befolgt?","menschen"],
  ["Wen würdest du als Trauzeugen nehmen?","Wer wäre dein Notfallkontakt?","menschen"],
  ["Wer feiert die besten Partys?","Bei wem bist du am liebsten zu Besuch?","menschen"],
  ["Wer hat dich zuletzt überrascht?","Von wem hättest du das nie erwartet?","menschen"],
  ["Was ist dein größtes Talent?","Worin bist du überraschend schlecht?","ich"],
  ["Was ist deine größte Angst?","Wovor hattest du als Kind Angst?","ich"],
  ["Nenne ein Wort, das du viel zu oft benutzt.","Nenne ein Wort, das du nicht leiden kannst.","ich"],
  ["Was schiebst du immer auf?","Was erledigst du sofort?","ich"],
  ["Worüber regst du dich zu schnell auf?","Was bringt dich sofort in gute Laune?","ich"],
  ["Was ist deine schlechteste Angewohnheit?","Was würdest du gern öfter machen?","ich"],
  ["Wobei kannst du richtig abschalten?","Was machst du, wenn dir langweilig ist?","ich"],
  ["Was sagst du, wenn du dich erschreckst?","Welches Schimpfwort rutscht dir zu oft raus?","ich"],
  ["Wofür stehst du früh auf?","Wofür würdest du eine Nacht durchmachen?","ich"],
  ["Was hast du zuletzt verloren?","Was suchst du ständig in deiner Wohnung?","ich"],
  ["Was kannst du einfach nicht wegwerfen?","Was hebst du auf, obwohl es kaputt ist?","ich"],
  ["Worüber lachst du, obwohl es albern ist?","Was findest du lustig, andere aber nicht?","ich"],
  ["Welchen Promi kannst du imitieren?","Wessen Stimme erkennst du am Telefon sofort?","ich"],
  ["Was ist dein Glücksbringer?","Welche Zahl ist deine Glückszahl?","ich"],
  ["Wovon träumst du immer wieder?","Was war dein seltsamster Traum?","ich"],
  ["Was macht dich sofort nervös?","Was beruhigt dich zuverlässig?","ich"],
  ["Was war dein peinlichster Moment?","Woran denkst du nachts und schämst dich?","ich"],
  ["Worauf bist du richtig stolz?","Womit kannst du bei anderen angeben?","ich"],
  ["Was würdest du an dir ändern?","Was magst du an dir?","ich"],
  ["Was ist dein größter Wunsch?","Was fehlt dir zum Glück?","ich"],
  ["Wann stehst du am liebsten auf?","Wann bist du am produktivsten?","ich"],
  ["Was ist dein größtes Vorurteil?","Wobei liegst du oft falsch?","ich"],
  ["Was hast du zuletzt gelernt?","Was möchtest du unbedingt noch lernen?","ich"],
  ["Was bereust du am meisten?","Was hast du getan und nie jemandem erzählt?","ich"],
  ["Wobei bist du besonders geduldig?","Wobei verlierst du sofort die Geduld?","ich"],
  ["Was ist dein größter Luxus?","Was gönnst du dir regelmäßig?","ich"],
  ["Was macht dich wütend?","Was macht dich traurig?","ich"],
  ["Wie gehst du mit Kritik um?","Wie reagierst du auf Lob?","ich"],
  ["Was ist dein Motto?","Welcher Satz begleitet dich?","ich"],
  ["Was war die beste Entscheidung deines Lebens?","Was hast du zuletzt spontan entschieden?","ich"],
  ["Wobei kannst du dich nicht entscheiden?","Was entscheidest du immer aus dem Bauch?","ich"],
  ["Wozu kannst du schwer Nein sagen?","Wozu sagst du zu oft Ja?","ich"],
  ["Was ist deine seltsamste Angewohnheit?","Was machst du, wenn wirklich niemand zuschaut?","ich"],
  ["Was macht dir wirklich Angst im Alltag?","Wovor drückst du dich?","ich"],
  ["Was ist bei dir immer ordentlich?","Wo bist du besonders pingelig?","ich"],
  ["Was war dein größter Erfolg im letzten Jahr?","Worauf freust du dich dieses Jahr?","ich"],
  ["Was ist deine Superkraft im Alltag?","Wofür fragen dich andere um Hilfe?","ich"],
  ["Wie zeigst du, dass du jemanden magst?","Woran merkt man, dass du schlechte Laune hast?","ich"],
  ["Was kaufst du dir, wenn es dir schlecht geht?","Was tröstet dich?","ich"],
  ["Was ist deine erste Erinnerung?","Was ist deine schönste Kindheitserinnerung?","ich"],
  ["Wobei bist du ehrgeizig?","Wobei ist dir das Ergebnis völlig egal?","ich"],
  ["Was ist deine größte Schwäche?","Was ist deine größte Stärke?","ich"],
  ["Wie erholst du dich am besten?","Was raubt dir am meisten Energie?","ich"],
  ["Worin bist du besser geworden?","Was konntest du früher besser?","ich"],
  ["Was ist dein liebstes Kompliment?","Welches Kompliment glaubst du nie?","ich"],
  ["Was ist dein schlimmster Fehlkauf an Kleidung?","Was hast du getragen und bereut?","ich"],
  ["Was hast du zuletzt zum ersten Mal gemacht?","Was traust du dich nicht?","ich"],
  ["Wie viel Zeit brauchst du für dich allein?","Wie viel Zeit verbringst du am Tag mit anderen?","ich"],
  ["Was ist dein Lieblingsgeruch?","Welcher Geruch erinnert dich an früher?","ich"],
  ["Welche Farbe trägst du am häufigsten?","Welche Farbe steht in deiner Wohnung im Vordergrund?","ich"],
  ["Was nimmst du auf eine einsame Insel mit?","Was hast du immer in der Tasche?","dinge"],
  ["Was ist das Teuerste, was du besitzt?","Was würdest du bei einem Brand als Erstes retten?","dinge"],
  ["Was liegt auf deinem Nachttisch?","Was liegt in deiner Hosentasche?","dinge"],
  ["Welches Möbelstück willst du loswerden?","Was in deiner Wohnung ist am ältesten?","dinge"],
  ["Über welches Geschenk hast du dich am meisten gefreut?","Welches Geschenk hast du weiterverschenkt?","dinge"],
  ["Welches Kleidungsstück trägst du am häufigsten?","Was hängt ungetragen in deinem Schrank?","dinge"],
  ["Was hast du zuletzt repariert?","Was ist bei dir gerade kaputt?","dinge"],
  ["Was war dein letzter Online-Kauf?","Was liegt gerade in deinem Warenkorb?","dinge"],
  ["Wofür sparst du gerade?","Was war deine letzte größere Anschaffung?","dinge"],
  ["Was war die beste Investition deines Lebens?","Wofür gibst du richtig gern Geld aus?","dinge"],
  ["Was war dein größter Fehlkauf?","Was bereust du gekauft zu haben?","dinge"],
  ["Wofür gibst du zu wenig Geld aus?","Wofür gibst du mehr aus, als du zugibst?","dinge"],
  ["Was würdest du dir kaufen, wenn Geld egal wäre?","Was steht seit Jahren auf deiner Wunschliste?","dinge"],
  ["Wie viel Bargeld hast du dabei?","Wie viel Bargeld liegt bei dir zuhause?","dinge"],
  ["Was hast du zuletzt verschenkt?","Was schenkst du am liebsten?","dinge"],
  ["Was liegt in deiner Geldbörse außer Geld?","Welche Karten trägst du immer bei dir?","dinge"],
  ["Was ist dein ältestes Kleidungsstück?","Was trägst du seit Jahren?","dinge"],
  ["Welches Gerät benutzt du täglich?","Ohne welches Gerät kämst du nicht aus?","dinge"],
  ["Was steht in deinem Keller?","Was lagerst du, obwohl du es nie brauchst?","dinge"],
  ["Was ist dein wertvollstes Erinnerungsstück?","Was hast du von deinen Großeltern?","dinge"],
  ["Was hast du zuletzt verkauft?","Was würdest du sofort verkaufen?","dinge"],
  ["Was kaufst du immer in großen Mengen?","Was hast du immer doppelt zuhause?","dinge"],
  ["Was ist bei dir die schlimmste Fehlinvestition gewesen?","Welches Abo hast du zu lange behalten?","dinge"],
  ["Was ist dein Lieblingsmöbelstück?","Wo sitzt du zuhause am liebsten?","dinge"],
  ["Was hast du geerbt?","Was möchtest du einmal weitergeben?","dinge"],
  ["Was ist das Verrückteste, was du gekauft hast?","Wofür hast du am meisten Geld ausgegeben?","dinge"],
  ["Wie viel gibst du im Monat für Klamotten aus?","Wie viel gibst du im Monat für Schuhe aus?","dinge"],
  ["Was leihst du niemals aus?","Was hast du verliehen und nie wiederbekommen?","dinge"],
  ["Was ist dein liebstes Werkzeug?","Was in deinem Haushalt kannst du selbst reparieren?","dinge"],
  ["Wie viel Geld hättest du gern auf dem Konto?","Ab welchem Betrag würdest du aufhören zu arbeiten?","dinge"],
  ["Was hängt bei dir an der Wand?","Was steht bei dir im Regal ganz oben?","dinge"],
  ["Was ist dein Lieblingsstück Kleidung im Winter?","Was ziehst du an, wenn es kalt ist?","dinge"],
  ["Welche Marke kaufst du immer wieder?","Welche Marke würdest du nie kaufen?","dinge"],
  ["Was hast du zuletzt aussortiert?","Was hebst du auf, obwohl du es nie brauchst?","dinge"],
  ["Was liegt in deiner Tasche, das da nicht hingehört?","Was schleppst du unnötig mit dir herum?","dinge"],
  ["Wie viel würdest du für ein gutes Bett ausgeben?","Wie viel würdest du für ein gutes Sofa ausgeben?","dinge"],
  ["Was ist bei dir Second Hand gekauft?","Was würdest du nie gebraucht kaufen?","dinge"],
  ["Was war dein erstes selbst verdientes Geld wert?","Wofür hast du dein erstes Gehalt ausgegeben?","dinge"],
  ["Welches Geschenk hat dich enttäuscht?","Was schenkt man dir zu oft?","dinge"],
  ["Was steht auf deinem Schreibtisch?","Was brauchst du beim Arbeiten immer griffbereit?","dinge"],
  ["Was ist deine liebste Kleinigkeit im Alltag?","Welche Kleinigkeit verdirbt dir sofort die Laune?","dinge"],
  ["Wie sparst du Geld?","Was ist dein bester Spartipp?","dinge"],
  ["Was ist das Nutzloseste, was du besitzt?","Was steht bei dir herum, ohne dass du weißt warum?","dinge"],
  ["Was hättest du gern doppelt?","Wovon hast du zu wenig?","dinge"],
  ["Was würdest du nie kaufen, egal wie günstig?","Was findest du völlig überteuert?","dinge"],
  ["Was ist dein Lieblingsstift?","Womit schreibst du?","dinge"],
  ["Was liegt in deinem Kulturbeutel?","Was nimmst du auf jede Reise mit?","dinge"],
  ["Welche Kleinigkeit macht deine Wohnung gemütlich?","Was fehlt deiner Wohnung noch?","dinge"],
  ["Was ist dein Lieblingsgeschenk, das du gemacht hast?","Was war dein kreativstes Geschenk?","dinge"],
  ["Wie viel Geld liegt gerade in deiner Jackentasche?","Wie viel Geld liegt bei dir zuhause herum?","dinge"],
  ["Welchen Beruf wolltest du als Kind?","Welchen Beruf könntest du niemals machen?","arbeit"],
  ["Welches Schulfach mochtest du am liebsten?","In welchem Schulfach warst du am schlechtesten?","arbeit"],
  ["Was nervt dich an deinem Job?","Was würdest du an deinem Arbeitsplatz sofort ändern?","arbeit"],
  ["Welchen Job würdest du gern einen Monat testen?","Was wärst du geworden, wenn alles möglich wäre?","arbeit"],
  ["Was war dein erster Job?","Womit hast du dein erstes eigenes Geld verdient?","arbeit"],
  ["Was machst du bei der Arbeit, wenn keiner hinschaut?","Womit vertreibst du dir die Zeit in langen Besprechungen?","arbeit"],
  ["Welches Fach hättest du in der Schule gebraucht?","Was hättest du gern früher gelernt?","arbeit"],
  ["Was war dein Lieblingslehrer-Fach?","Welchen Lehrer konntest du nicht leiden?","arbeit"],
  ["Wie war dein Abschlusszeugnis?","In welchem Fach hattest du die beste Note?","arbeit"],
  ["Was hast du in der Schule geschwänzt?","Was hast du im Job schon einmal vorgetäuscht?","arbeit"],
  ["Was ist der beste Teil deines Arbeitstags?","Was ist der zäheste Teil deines Arbeitstags?","arbeit"],
  ["Wie sieht dein Schreibtisch bei der Arbeit aus?","Was steht auf deinem Arbeitsplatz Persönliches?","arbeit"],
  ["Was isst du in der Mittagspause?","Wo isst du bei der Arbeit?","arbeit"],
  ["Wie lange dauert dein Arbeitsweg?","Wie lange dauert deine Mittagspause?","arbeit"],
  ["Wo arbeitest du am liebsten?","Wo arbeitest du am konzentriertesten?","arbeit"],
  ["Was war dein schlimmstes Bewerbungsgespräch?","Wobei bist du schon durchgefallen?","arbeit"],
  ["Welchen Kollegen würdest du zum Feierabendbier einladen?","Mit wem redest du bei der Arbeit am meisten?","arbeit"],
  ["Was ist dein größter Fehler im Job gewesen?","Was ist dir bei der Arbeit Peinliches passiert?","arbeit"],
  ["Wie viele Meetings hast du diese Woche?","Wie viele davon sind überflüssig?","arbeit"],
  ["Wann machst du am liebsten Feierabend?","Wann gehst du tatsächlich?","arbeit"],
  ["Was wäre dein Traumberuf ohne Ausbildung?","Was könntest du sofort anfangen zu arbeiten?","arbeit"],
  ["Was steht in deiner Signatur?","Wie beginnst du eine Mail?","arbeit"],
  ["Was war dein Lieblingsplatz in der Schule?","Wo hast du in der Klasse gesessen?","arbeit"],
  ["Was hast du in der Schulpause gemacht?","Was hattest du in der Brotdose?","arbeit"],
  ["Welchen Schulausflug erinnerst du noch?","Wohin ging deine Klassenfahrt?","arbeit"],
  ["Was hältst du von Gruppenarbeit?","Was war dein schlimmstes Referat?","arbeit"],
  ["Wie lernst du am besten?","Wie hast du für Prüfungen gelernt?","arbeit"],
  ["Was ist dein größter beruflicher Wunsch?","Wo willst du in fünf Jahren stehen?","arbeit"],
  ["Was würdest du deinem Chef gern sagen?","Was schätzt du an deinem Chef?","arbeit"],
  ["Welche Software nutzt du bei der Arbeit am meisten?","Welches Programm nervt dich täglich?","arbeit"],
  ["Wie viele Urlaubstage hast du noch?","Wie viele Urlaubstage nimmst du am Stück?","arbeit"],
  ["Wie viele Aufgaben warten nach dem Urlaub auf dich?","Wie viele Aufgaben schiebst du gerade vor dir her?","arbeit"],
  ["Was ist bei euch der Klassiker im Pausenraum?","Wer kocht bei euch den Kaffee?","arbeit"],
  ["Welchen Nebenjob hattest du als Schüler?","Was war dein Ferienjob?","arbeit"],
  ["Was macht einen guten Kollegen aus?","Was macht einen schlechten Chef aus?","arbeit"],
  ["Wie gehst du mit Stress im Job um?","Was machst du, wenn du überfordert bist?","arbeit"],
  ["Was hast du im Studium oder in der Ausbildung gelernt, das du nie brauchtest?","Was war praktisch am nützlichsten?","arbeit"],
  ["Was würdest du an der Schule ändern?","Welches Fach sollte es geben?","arbeit"],
  ["Wann hast du zuletzt eine Gehaltserhöhung bekommen?","Wann hast du zuletzt über Geld verhandelt?","arbeit"],
  ["Was machst du in der letzten Stunde vor Feierabend?","Was schiebst du auf den nächsten Tag?","arbeit"],
  ["Was ist deine erste Aufgabe am Morgen?","Womit endet dein Arbeitstag?","arbeit"],
  ["Welche Kleidung trägst du bei der Arbeit?","Wie streng ist eure Kleiderordnung?","arbeit"],
  ["Was war deine schönste Zeit in der Schule?","In welcher Klasse ging es dir am besten?","arbeit"],
  ["Was ist deine größte Ablenkung im Job?","Was lenkt dich zuhause am meisten ab?","arbeit"],
  ["Was würdest du beruflich noch einmal genauso machen?","Was würdest du beruflich anders machen?","arbeit"],
  ["Was ist die schlimmste Aufgabe in deinem Job?","Was machst du am liebsten bei der Arbeit?","arbeit"],
  ["Was war das Beste an deiner Ausbildung?","Was war das Schwerste am Anfang?","arbeit"],
  ["Wie ordentlich ist dein Schreibtisch?","Wie ordentlich ist dein Mailpostfach?","arbeit"],
  ["Was sagst du, wenn dich jemand nach deinem Beruf fragt?","Wie erklärst du deinen Job Kindern?","arbeit"],
  ["Was würdest du machen, wenn du morgen gekündigt würdest?","Was ist dein Plan B?","arbeit"],
  ["Welche App nutzt du am meisten?","Welche App würdest du sofort löschen?","medien"],
  ["Welche App öffnest du morgens zuerst?","Welche App hast du zuletzt installiert?","medien"],
  ["Welches Emoji benutzt du am meisten?","Welches Emoji verstehst du nicht?","medien"],
  ["Wem folgst du, ohne es zuzugeben?","Welchen Kanal schaust du regelmäßig?","medien"],
  ["Welches Buch hast du nie zu Ende gelesen?","Welches Buch würdest du weiterempfehlen?","kultur"],
  ["Welchen Podcast hörst du?","Was hörst du beim Autofahren?","medien"],
  ["Wo liest du deine Nachrichten?","Welche Nachrichtenquelle vertraust du?","medien"],
  ["Welche App zeigt dir die meiste Bildschirmzeit?","Welche App hast du aus Frust gelöscht?","medien"],
  ["Was war dein erstes soziales Netzwerk?","Welches Netzwerk nutzt du heute nicht mehr?","medien"],
  ["Wie sieht dein Startbildschirm aus?","Welche App liegt bei dir ganz unten in der Leiste?","medien"],
  ["Wie viele Fotos sind auf deinem Handy?","Wie viele Fotos hast du dieses Jahr gemacht?","medien"],
  ["Was googelst du am häufigsten?","Was war deine letzte Suchanfrage?","medien"],
  ["Welches Video hast du zuletzt geteilt?","Was schickst du deinen Freunden am häufigsten?","medien"],
  ["Wie ist dein Handyhintergrund?","Was ist dein Profilbild?","medien"],
  ["Wie viele Gruppenchats hast du?","Wie viele davon hast du stummgeschaltet?","medien"],
  ["Wer antwortet dir immer sofort?","Wen lässt du am längsten warten?","medien"],
  ["Wie viele Freunde hast du online?","Wie viele davon kennst du wirklich?","medien"],
  ["Welche Webseite besuchst du täglich?","Welche Seite öffnest du, wenn dir langweilig ist?","medien"],
  ["Welches Buch liest du gerade?","Welches Buch liegt seit Monaten angefangen herum?","medien"],
  ["Wo liest du unterwegs?","Wo liest du zuhause am liebsten?","medien"],
  ["Was ist dein Lieblings-Hörbuch?","Was hörst du beim Einschlafen?","medien"],
  ["Welche Zeitschrift liest du?","Welche Zeitung lag bei euch früher zuhause?","medien"],
  ["Was ist dein liebstes Meme?","Über welchen Internettrend lachst du?","medien"],
  ["Welchen Onlineshop nutzt du am meisten?","Wo bestellst du fast nie?","medien"],
  ["Wie viele Streamingdienste hast du?","Wie viele davon nutzt du wirklich?","medien"],
  ["Wie merkst du dir deine Passwörter?","Wo bewahrst du sie auf?","medien"],
  ["Wie viele Geräte hast du gleichzeitig an?","Wie viele Bildschirme hast du zuhause?","medien"],
  ["Wie lange dauert es, bis du das Internet vermisst?","Wie lange hältst du ohne WLAN aus?","medien"],
  ["Welche Werbung nervt dich am meisten?","Welches Wort im Internet kannst du nicht mehr hören?","medien"],
  ["Welchen YouTube-Kanal empfiehlst du?","Was schaust du beim Essen?","medien"],
  ["Wie lange hattest du dein erstes Handy?","Wie lange behältst du ein Handy?","medien"],
  ["Was ist dein Klingelton?","Welches Geräusch macht dein Wecker?","medien"],
  ["Wie viele Benachrichtigungen bekommst du am Tag?","Wie viele Benachrichtigungen hast du ausgeschaltet?","medien"],
  ["Was war dein längster Videoanruf?","Mit wem telefonierst du am liebsten per Video?","medien"],
  ["Wie viele Newsletter bekommst du?","Wie viele davon liest du wirklich?","medien"],
  ["Von wem bekommst du die längsten Sprachnachrichten?","Wem schickst du am meisten Sprachnachrichten?","medien"],
  ["Was hast du zuletzt online gelernt?","Welches Tutorial hat dir geholfen?","medien"],
  ["Welche Karte-App nutzt du?","Welches Navi benutzt du im Auto?","medien"],
  ["Was ist dein liebster Blog oder Newsletter?","Wem folgst du wegen guter Inhalte?","medien"],
  ["Wie viele Passwörter hast du gespeichert?","Wie oft musst du ein Passwort zurücksetzen?","medien"],
  ["Was ist dein liebstes Suchergebnis-Kaninchenloch?","Welches unnütze Wissen hast du im Kopf?","medien"],
  ["Wie oft postest du selbst etwas?","Wie oft löschst du einen Beitrag wieder?","medien"],
  ["Welche Kommentare liest du dir durch?","Was war dein letzter Kommentar?","medien"],
  ["Wie viele E-Mail-Adressen hast du?","Wie viele davon nutzt du noch?","medien"],
  ["Was ist dein Lieblings-Comic oder Webcomic?","Welche Bildergeschichte magst du?","medien"],
  ["Welchen Livestream schaust du?","Wem würdest du beim Arbeiten zuschauen?","medien"],
  ["Wie viele Cloudspeicher nutzt du?","Wie viele Dateien liegen auf deinem Schreibtisch?","medien"],
  ["Welche Erweiterung nutzt du im Browser?","Welchen Browser benutzt du?","medien"],
  ["Was ist die längste Serie an Tagen, die du eine App genutzt hast?","Welche App öffnest du aus Gewohnheit?","medien"],
  ["Was war das Beste, was du je online gefunden hast?","Was hast du online gekauft und geliebt?","medien"],
  ["Was ist dein Lieblingsfeiertag?","Welchen Feiertag findest du überflüssig?","feste"],
  ["Welches Wetter magst du am liebsten?","Bei welchem Wetter bleibst du lieber zuhause?","feste"],
  ["Was gehört für dich zu Weihnachten?","Was gibt es bei euch an Heiligabend zu essen?","feste"],
  ["Wie feierst du deinen Geburtstag?","Was wünschst du dir zum Geburtstag?","feste"],
  ["Was machst du an einem verregneten Sonntag?","Was machst du an einem Tag, an dem nichts klappt?","feste"],
  ["Welche Jahreszeit magst du am liebsten?","In welcher Jahreszeit bist du am aktivsten?","feste"],
  ["Worauf freust du dich im Sommer am meisten?","Was machst du beim ersten warmen Tag im Jahr?","feste"],
  ["Wie verbringst du Silvester?","Was war dein bester Jahreswechsel?","feste"],
  ["Was ist dein Neujahrsvorsatz?","Welchen Vorsatz hast du nie eingehalten?","feste"],
  ["Was schenkst du zu Weihnachten?","Was wünschst du dir dieses Jahr?","feste"],
  ["Was hängst du im Winter in die Fenster?","Was steht bei dir zu Weihnachten im Wohnzimmer?","feste"],
  ["Ab wann darf bei dir Weihnachtsdeko stehen?","Ab wann darf Weihnachtsmusik laufen?","feste"],
  ["Was isst du an Ostern?","Wie habt ihr früher Ostern gefeiert?","feste"],
  ["Was machst du an Halloween?","Als was würdest du dich verkleiden?","feste"],
  ["Wie feierst du Karneval oder Fasching?","Was war dein bestes Kostüm?","feste"],
  ["Was machst du am 1. Mai?","Wohin gehst du an einem Feiertag?","feste"],
  ["Wie verbringst du deinen Sommerurlaub am liebsten?","Was fehlt dir im Winter am meisten?","feste"],
  ["Was magst du am Herbst?","Was nervt dich am Herbst?","feste"],
  ["Was ist dein liebstes Winteressen?","Was trinkst du, wenn es kalt ist?","feste"],
  ["Wann hast du zuletzt im Schnee gespielt?","Wann hast du zuletzt einen Schneemann gebaut?","feste"],
  ["Was ist dein liebstes Frühlingsgefühl?","Woran merkst du, dass der Frühling da ist?","feste"],
  ["Was gehört für dich zum Jahrmarkt?","Was fährst du auf dem Jahrmarkt?","feste"],
  ["Was isst du auf dem Weihnachtsmarkt?","Was trinkst du auf dem Weihnachtsmarkt?","feste"],
  ["Wie feierst du Muttertag?","Was schenkst du deinen Eltern?","feste"],
  ["Was war deine beste Geburtstagsfeier?","Wen lädst du zu deinem Geburtstag ein?","feste"],
  ["Welchen Jahrestag feierst du jedes Jahr?","Welchen Jahrestag vergisst du immer?","feste"],
  ["Was machst du an einem Brückentag?","Wie planst du deine Feiertage?","feste"],
  ["Was ist dein liebstes Sommergetränk?","Was trinkst du am Pool oder Strand?","feste"],
  ["Wie überstehst du Hitze?","Was machst du bei 35 Grad?","feste"],
  ["Was machst du bei Dauerregen?","Wie überstehst du den November?","feste"],
  ["Was ist dein Lieblingsmonat?","Welchen Monat magst du am wenigsten?","feste"],
  ["Wie viele Geschenke kaufst du im Jahr?","Wie viele Geschenke bekommst du im Jahr?","feste"],
  ["Was gehört zu einem guten Grillabend?","Was grillst du am liebsten?","feste"],
  ["Was war deine schönste Feier?","Auf welcher Party warst du zuletzt?","feste"],
  ["Wie feiert deine Familie?","Was ist bei euch Tradition?","feste"],
  ["Wie hältst du es mit Feuerwerk?","Was ist dein Silvester-Ritual?","feste"],
  ["Was tust du am Tag nach einer Feier?","Wie erholst du dich von einer langen Nacht?","feste"],
  ["Was schmückst du zu Ostern?","Was gehört bei euch zum Osterfrühstück?","feste"],
  ["Welchen Feiertag kennst du nur dem Namen nach?","Welchen Brauch verstehst du nicht?","feste"],
  ["Was ist dein liebstes Winterkleidungsstück?","Welche Mütze trägst du?","feste"],
  ["Wann räumst du die Weihnachtsdeko weg?","Wann stellst du den Baum auf?","feste"],
  ["Was machst du an einem Feiertag, an dem alles zu hat?","Was tust du, wenn alle anderen keine Zeit haben?","feste"],
  ["Wo verbringst du Weihnachten?","Wen besuchst du an den Feiertagen?","feste"],
  ["Was ist dein Lieblingsplätzchen?","Was backt ihr in der Weihnachtszeit?","feste"],
  ["Was war das schönste Geschenk deiner Kindheit?","Woran erinnerst du dich von früheren Festen?","feste"],
  ["Wie feierst du kleine Erfolge?","Womit belohnst du dich nach einer bestandenen Prüfung?","feste"],
  ["Was ist dein Lieblingsfest im Ausland?","Welches fremde Fest würdest du gern erleben?","feste"],
  ["Wie viele Feiern hast du dieses Jahr?","Wie viele Einladungen hast du dieses Jahr abgesagt?","feste"],
  ["Was ziehst du an, wenn du zu einer Feier gehst?","Was ziehst du an, wenn du zuhause bleibst?","feste"],
  ["Was ist dein liebstes Ferienziel im Winter?","Wohin fährst du im Winter?","feste"],
  ["Welche Sportart machst du am liebsten?","Welche Sportart schaust du am liebsten?","sport"],
  ["Wie oft warst du diesen Monat im Fitnessstudio?","Wie oft hast du es dir fest vorgenommen?","sport"],
  ["Welche Sportart hast du als Kind gemacht?","Welche Sportart würdest du gern neu anfangen?","sport"],
  ["Welchen Verein feuerst du an?","Welchen Verein kannst du nicht ausstehen?","sport"],
  ["Wie weit bist du am Stück gelaufen?","Wie weit läufst du normalerweise?","sport"],
  ["Welche Übung im Training hasst du?","Welche Übung fällt dir am leichtesten?","sport"],
  ["Bei welcher Sportart wärst du sofort verletzt?","Welche Sportart sieht einfacher aus, als sie ist?","sport"],
  ["Welchen Sportler bewunderst du?","Welchen Sportler findest du überschätzt?","sport"],
  ["Was ziehst du zum Sport an?","Was liegt ungenutzt in deiner Sporttasche?","sport"],
  ["Wann am Tag trainierst du?","Wann hättest du am meisten Energie?","sport"],
  ["Wie lange dauert dein Training?","Wie lange dauert dein Spaziergang?","sport"],
  ["Welches Turnier schaust du jedes Mal?","Welches Sportereignis lässt dich völlig kalt?","sport"],
  ["Welche Sportart würdest du live im Stadion sehen wollen?","Welche schaust du lieber zuhause?","sport"],
  ["Was war dein größter sportlicher Erfolg?","Woran bist du sportlich gescheitert?","sport"],
  ["Wie viele Liegestütze schaffst du?","Wie viele Klimmzüge schaffst du?","sport"],
  ["Welchen Muskelkater hattest du zuletzt?","Was tut nach dem Training immer weh?","sport"],
  ["Mit wem trainierst du am liebsten?","Wer motiviert dich am meisten?","sport"],
  ["Welche Wintersportart magst du?","Welche Wassersportart magst du?","sport"],
  ["Welche Sportart würdest du deinen Kindern empfehlen?","Welche Sportart findest du sinnlos?","sport"],
  ["Wie weit ist dein Fitnessstudio entfernt?","Wie weit ist dein Lieblingsrestaurant entfernt?","sport"],
  ["Was hörst du beim Sport?","Was denkst du beim Laufen?","sport"],
  ["Welches Sportgerät hast du zuhause?","Welches Sportgerät staubt bei dir ein?","sport"],
  ["Wie oft dehnst du dich wirklich?","Wie oft solltest du dich dehnen?","sport"],
  ["Welche Sportart hast du im Schulsport gehasst?","Worin warst du im Schulsport gut?","sport"],
  ["Wie viele Tore hast du in deinem Leben geschossen?","Wie viele Spiele hast du gewonnen?","sport"],
  ["Welchen Trainer hast du in Erinnerung?","Wer hat dir Sport beigebracht?","sport"],
  ["Was wäre dein Sport, wenn Geld keine Rolle spielt?","Welche Sportart ist dir zu teuer?","sport"],
  ["Was ist dein sportliches Ziel für dieses Jahr?","Was hast du dir letztes Jahr vorgenommen?","sport"],
  ["Welches Album kennst du komplett?","Welches Album hast du am häufigsten gehört?","musik"],
  ["Welcher Künstler begleitet dich seit Jahren?","Welchen Künstler hast du früher gehört und heute nicht mehr?","musik"],
  ["Welches Konzert war dein bestes?","Zu welchem Konzert würdest du morgen fahren?","musik"],
  ["Welches Lied singst du unter der Dusche?","Welches Lied singst du im Auto mit?","musik"],
  ["Welches Instrument spielst du?","Welches Instrument wolltest du immer lernen?","musik"],
  ["Welches Lied läuft auf deiner Beerdigung?","Welches Lied läuft auf deiner Hochzeit?","musik"],
  ["Welchen Song findest du peinlich gut?","Welchen Song gibst du nicht gern zu?","musik"],
  ["Was läuft bei dir zum Aufwachen?","Was läuft bei dir zum Einschlafen?","musik"],
  ["Welches Musikgenre verstehst du nicht?","Welches Genre magst du erst seit Kurzem?","musik"],
  ["Wo hörst du Musik am lautesten?","Wo hörst du am meisten Musik?","musik"],
  ["Welcher Songtext geht dir nahe?","Welcher Songtext ergibt für dich keinen Sinn?","musik"],
  ["Welches Lied verbindest du mit dem Sommer?","Welches Lied verbindest du mit deiner Jugend?","musik"],
  ["Welchen Ohrwurm hattest du zuletzt?","Welches Lied bekommst du nicht mehr los?","musik"],
  ["Wie viel würdest du für ein Konzertticket ausgeben?","Wie viel hat dein teuerstes Ticket gekostet?","musik"],
  ["Welche Band würdest du wiedervereinigen?","Welche Band hätte früher aufhören sollen?","musik"],
  ["Welches Lied hörst du beim Putzen?","Welches Lied hörst du beim Kochen?","musik"],
  ["Welchen Künstler würdest du live sehen, egal wo?","Wen hast du live gesehen und warst enttäuscht?","musik"],
  ["Welche CD lag früher in deinem Zimmer?","Was war deine erste eigene Musik?","musik"],
  ["Welches Lied macht dich sofort traurig?","Welches Lied macht dich sofort fröhlich?","musik"],
  ["Was singst du beim Karaoke?","Was würdest du nie beim Karaoke singen?","musik"],
  ["Welchen deutschen Song magst du?","Welchen deutschen Song findest du furchtbar?","musik"],
  ["Welche Musik lief bei deinen Eltern?","Welche Musik hast du von deinen Eltern übernommen?","musik"],
  ["Wie viele Lieder hast du gespeichert?","Wie viele davon hörst du wirklich?","musik"],
  ["Welches Musikvideo ist dir im Kopf geblieben?","Welches Cover eines Albums kennst du auswendig?","musik"],
  ["Welcher Song passt zu deinem Leben?","Welcher Song beschreibt deinen Tag heute?","musik"],
  ["Wann hörst du am lautesten Musik?","Wann drehst du sofort lauter?","musik"],
  ["Welchen Radiosender hörst du?","Welchen Sender schaltest du sofort weg?","musik"],
  ["Welches Festival würdest du besuchen?","Auf welchem Festival warst du schon?","musik"],
  ["Welches Lied hat dein Handy als Klingelton?","Welchen Weckton benutzt du?","musik"],
  ["Welchen Song würdest du in die Zukunft schicken?","Welcher Song erklärt unsere Zeit?","musik"],
  ["Welchen Film schaust du an Weihnachten?","Welchen Film schaust du, wenn du krank bist?","filme"],
  ["Welche Serie hast du am schnellsten durchgeschaut?","Welche Serie ziehst du ewig hin?","filme"],
  ["Welcher Filmschurke ist der beste?","Welcher Filmheld ist überbewertet?","filme"],
  ["Welchen Film findest du besser als das Buch?","Welches Buch ist besser als der Film?","filme"],
  ["Welchen Film hast du im Kino gesehen?","Welchen Film würdest du gern im Kino sehen?","filme"],
  ["Welcher Film hat dich zum Weinen gebracht?","Welcher Film hat dich richtig erschreckt?","filme"],
  ["Welche Serie würdest du weiterempfehlen?","Von welcher Serie rätst du ab?","filme"],
  ["Welchen Schauspieler magst du?","Welchen Schauspieler kannst du nicht ernst nehmen?","filme"],
  ["Welcher Filmsatz ist dir geblieben?","Welchen Satz zitierst du aus einem Film?","filme"],
  ["Was isst du beim Filmschauen?","Was trinkst du beim Filmschauen?","filme"],
  ["Welchen Film schaust du zum zehnten Mal?","Welchen Film würdest du gern zum ersten Mal sehen?","filme"],
  ["Welches Serienfinale hat dich enttäuscht?","Welches Serienfinale war perfekt?","filme"],
  ["Welcher Zeichentrickfilm gehört zu deiner Kindheit?","Welche Kinderserie hast du geliebt?","filme"],
  ["Was machst du nebenbei beim Filmschauen?","Was nervt dich beim Filmschauen am meisten?","filme"],
  ["Welchen Film würdest du deinem Partner zeigen?","Welchen Film versteht außer dir niemand?","filme"],
  ["Welche Filmreihe hast du komplett gesehen?","Welche Filmreihe hättest du beenden sollen?","filme"],
  ["Wie viele Folgen schaust du am Stück?","Wie viele Folgen wolltest du eigentlich schauen?","filme"],
  ["Welcher Film ist zu lang?","Welcher Film ist zu kurz?","filme"],
  ["Welche Rolle würdest du in einem Film spielen?","In welchem Film würdest du gern leben?","filme"],
  ["Welche Dokumentation fandest du stark?","Über welches Thema würdest du eine Doku schauen?","filme"],
  ["Welcher Soundtrack ist besser als der Film?","Welche Filmmusik erkennst du sofort?","filme"],
  ["Welchen Film hast du abgebrochen?","Welchen Film hast du zu Ende geschaut, obwohl er schlecht war?","filme"],
  ["Welche Serie schauen alle außer dir?","Welche Serie kennt sonst keiner?","filme"],
  ["Welchen Film schaust du an einem Sonntag?","Was läuft bei dir nebenbei?","filme"],
  ["Welcher Film war deiner Kindheit zu gruselig?","Welchen Film durftest du nicht sehen?","filme"],
  ["Welchen Filmtitel findest du albern?","Welcher deutsche Filmtitel ist misslungen?","filme"],
  ["Was ist dir am Kino wichtig?","Was stört dich im Kino?","filme"],
  ["Welchen Film würdest du neu drehen?","Welches Ende würdest du ändern?","filme"],
  ["Welche Nebenfigur ist besser als die Hauptfigur?","Welche Figur nervt dich?","filme"],
  ["Welche Streaming-Anbieter zahlst du?","Welchen davon nutzt du kaum?","filme"],
  ["Welches Spiel hast du zuletzt gespielt?","Welches Spiel liegt ungespielt herum?","games"],
  ["Auf welcher Konsole hast du angefangen?","Welche Konsole hättest du gern gehabt?","games"],
  ["Welches Spiel hast du durchgespielt?","Welches Spiel hast du kurz vor Schluss aufgegeben?","games"],
  ["Welcher Bosskampf hat dich zur Verzweiflung gebracht?","Welche Stelle hast du zwanzigmal wiederholt?","games"],
  ["Welches Brettspiel spielt ihr in der Familie?","Bei welchem Spiel gibt es immer Streit?","games"],
  ["Welches Kartenspiel kannst du auswendig?","Welches Spiel erklärst du am schlechtesten?","games"],
  ["Welchen Spielcharakter magst du?","Als wen spielst du am liebsten?","games"],
  ["Wie lange spielst du am Stück?","Wie lange wolltest du eigentlich spielen?","games"],
  ["Welches Handyspiel hast du zu lange gespielt?","Welches Spiel hast du wieder gelöscht?","games"],
  ["Gegen wen spielst du am liebsten?","Mit wem spielst du am liebsten?","games"],
  ["Welches Spiel aus deiner Kindheit vermisst du?","Welches Spiel würdest du heute noch anfassen?","games"],
  ["Was war dein erstes eigenes Spiel?","Was war dein letzter Spielekauf?","games"],
  ["Welches Spiel ist besser als sein Ruf?","Welches Spiel ist überbewertet?","games"],
  ["Welche Spielwelt würdest du besuchen?","In welcher Spielwelt würdest du keine Nacht überleben?","games"],
  ["Was nervt dich beim Online-Spielen?","Was bringt dich beim Spielen auf die Palme?","games"],
  ["Wie viele Spiele hast du ungespielt gekauft?","Wie viele davon hast du nie gestartet?","games"],
  ["Welches Spiel spielst du zum Abschalten?","Welches Spiel fordert dich richtig?","games"],
  ["Womit spielst du am liebsten?","Womit spielst du am schnellsten?","games"],
  ["Welches Rennspiel magst du?","Welches Sportspiel magst du?","games"],
  ["Welche Spielfigur würdest du als Tattoo tragen?","Welches Spiellogo erkennst du sofort?","games"],
  ["Welchen Trick kennst du in einem Spiel?","Wo hast du schon mal geschummelt?","games"],
  ["Welches Spiel hast du deinen Eltern gezeigt?","Welches Spiel hat jemand für dich gespielt?","games"],
  ["Wie viele Stunden hast du in dein Lieblingsspiel gesteckt?","Wie viel Zeit gibst du einem neuen Spiel?","games"],
  ["Welches Spiel würdest du auf eine Insel mitnehmen?","Welches Spiel könntest du ewig spielen?","games"],
  ["Was war dein schlimmster Fehlkauf im Spielbereich?","Was war dein bester Kauf?","games"],
  ["Welche Musik läuft beim Spielen?","Was hörst du beim Spielen nebenbei?","games"],
  ["Welche Herausforderung würdest du im Spiel annehmen?","Wo gibst du sofort auf?","games"],
  ["Welches Spiel spielt ihr zu Silvester?","Welches Spiel geht immer auf Partys?","games"],
  ["Wer in deinem Umfeld spielt am meisten?","Wer gewinnt bei euch fast immer?","games"],
  ["Welches Spiel wünschst du dir als Verfilmung?","Welche Verfilmung eines Spiels war schlecht?","games"],
  ["Welches Haustier hast du oder hattest du?","Welches Haustier hättest du gern?","tiere"],
  ["Wie heißt dein Haustier?","Wie würdest du einen Hund nennen?","tiere"],
  ["Welches Tier passt zu dir?","Welches Tier passt gar nicht zu dir?","tiere"],
  ["Welches Tier findest du am schönsten?","Welches Tier findest du unheimlich?","tiere"],
  ["Welches Tier würdest du im Zoo zuerst besuchen?","Welches Gehege lässt du aus?","tiere"],
  ["Welches Tier hast du in freier Natur gesehen?","Welches Tier möchtest du einmal sehen?","tiere"],
  ["Welches Insekt ekelt dich?","Vor welchem Tier hast du echt Angst?","tiere"],
  ["Welches Tier ist klüger, als man denkt?","Welches Tier wird überschätzt?","tiere"],
  ["Was frisst dein Haustier am liebsten?","Was klaut dein Haustier vom Tisch?","tiere"],
  ["Wie viel Zeit verbringst du täglich mit deinem Tier?","Wie lange bist du täglich mit dem Tier draußen?","tiere"],
  ["Welches Tiergeräusch kannst du nachmachen?","Welches Tiergeräusch nervt dich?","tiere"],
  ["Welches Tier würdest du retten wollen?","Für welches Tier würdest du spenden?","tiere"],
  ["Welches Nutztier hast du schon gestreichelt?","Auf welchem Bauernhof warst du zuletzt?","tiere"],
  ["Welches Tier wäre ein guter Mitbewohner?","Welches Tier würde deine Wohnung zerstören?","tiere"],
  ["Welches Tier im Wasser fasziniert dich?","Welches Tier im Wasser macht dir Angst?","tiere"],
  ["Welchen Vogel erkennst du am Gesang?","Welchen Vogel siehst du täglich?","tiere"],
  ["Welches Tier hat einen unpassenden Namen?","Welches Tier hat den schönsten Namen?","tiere"],
  ["Welches Tier würdest du niemals essen?","Welches Tier isst du regelmäßig?","tiere"],
  ["Welcher Hund passt zu dir?","Welcher Hund wäre dir zu viel?","tiere"],
  ["Welches Tier hast du als Kind gepflegt?","Welches Tier hattest du in der Schule im Klassenzimmer?","tiere"],
  ["Welches Tier ist im Sommer am nervigsten?","Welches Tier merkt man erst im Winter?","tiere"],
  ["Welches Tier würdest du im Garten willkommen heißen?","Welches Tier soll draußen bleiben?","tiere"],
  ["Wie viele Tiere leben in deinem Haushalt?","Wie viele Tiere hattest du insgesamt?","tiere"],
  ["Welche Tierdoku hast du gesehen?","Über welches Tier weißt du erstaunlich viel?","tiere"],
  ["Welches Tier ist dein Krafttier?","Welches Tier siehst du in dir?","tiere"],
  ["Was macht dein Tier, wenn du nach Hause kommst?","Was macht dein Tier nachts?","tiere"],
  ["Welches ausgestorbene Tier würdest du sehen wollen?","Welches Fabelwesen hättest du gern?","tiere"],
  ["Was war dein teuerster Tierarztbesuch?","Was gibst du im Monat für dein Tier aus?","tiere"],
  ["Welches Tier würdest du im Urlaub mitnehmen?","Wer passt auf dein Tier auf?","tiere"],
  ["Welches Tier hat dich schon mal gebissen?","Welchem Tier bist du knapp entkommen?","tiere"],
  ["Welche Automarke gefällt dir?","Welche Automarke würdest du nie kaufen?","autos"],
  ["Welches Auto steht in deiner Einfahrt?","Welches Auto stand früher bei deinen Eltern?","autos"],
  ["Welches Auto ist dein Traumwagen?","Welches Auto könntest du dir gerade leisten?","autos"],
  ["Womit fährst du am liebsten?","Womit hast du Fahren gelernt?","autos"],
  ["Wie oft wäschst du dein Auto?","Wie oft saugst du dein Auto aus?","autos"],
  ["Was hängt an deinem Rückspiegel?","Was liegt auf deinem Beifahrersitz?","autos"],
  ["Welche Farbe hat dein Auto?","Welche Autofarbe würdest du nie wählen?","autos"],
  ["Wie viele Kilometer fährst du im Monat?","Wie weit fährst du mit einer Tankfüllung?","autos"],
  ["Welches Auto würdest du sammeln?","Welcher Oldtimer gefällt dir?","autos"],
  ["Wie schnell bist du je gefahren?","Wie schnell darf man auf deinem Arbeitsweg fahren?","autos"],
  ["Was war dein schlimmster Parkversuch?","Wo parkst du nie freiwillig?","autos"],
  ["Auf welcher Straße fährst du am liebsten?","Welche Strecke kennst du im Schlaf?","autos"],
  ["Was spricht für dich für ein Elektroauto?","Was hält dich vom Umsteigen ab?","autos"],
  ["Was nervt dich an anderen Autofahrern?","Was machst du selbst, obwohl es nervt?","autos"],
  ["Wie alt warst du beim Führerschein?","Wie alt warst du bei deinem ersten eigenen Auto?","autos"],
  ["Welches Motorrad gefällt dir?","Welches Motorrad würdest du nie fahren?","autos"],
  ["Was ist dein längster Roadtrip?","Wohin würdest du mit dem Auto fahren?","autos"],
  ["Was hörst du beim Autofahren am liebsten?","Was hörst du, wenn du allein fährst?","autos"],
  ["Welche Panne hattest du schon?","Was hast du am Auto selbst repariert?","autos"],
  ["Wie viele Autos hattest du bisher?","Wie viele Autos hattet ihr in der Familie?","autos"],
  ["Was würdest du an deinem Auto sofort ändern?","Welche Ausstattung fehlt dir?","autos"],
  ["Wie viel darf ein Auto kosten?","Wie viel hat dein teuerstes Fahrzeug gekostet?","autos"],
  ["Welches Nummernschild hättest du gern?","Woran erkennt man dein Auto?","autos"],
  ["Was gefällt dir am Autofahren?","Was stört dich am Autofahren?","autos"],
  ["Welches Werkzeug liegt in deinem Kofferraum?","Was fehlt in deinem Auto für den Notfall?","autos"],
  ["Welchen Wagen fahren deine Freunde?","Welches Auto passt zu deinem Charakter?","autos"],
  ["Wie viele Kilometer hat dein Auto?","Wie viele Kilometer soll es noch schaffen?","autos"],
  ["Welches Fahrzeug würdest du mieten?","Welchen Wagen würdest du im Urlaub fahren?","autos"],
  ["Was ist dein größter Ärger mit der Werkstatt?","Was ging an deinem Auto zuletzt kaputt?","autos"],
  ["Welche Technik im Auto findest du überflüssig?","Welche Technik möchtest du nicht mehr missen?","autos"],
  ["Welchen Autor liest du gern?","Welchen Klassiker hast du nie gelesen?","kultur"],
  ["In welchem Museum warst du zuletzt?","In welches Museum wolltest du immer mal?","kultur"],
  ["Welches Kunstwerk kennst du?","Welches Kunstwerk verstehst du nicht?","kultur"],
  ["Welche Sprache würdest du lernen?","Welche Sprache klingt für dich am schönsten?","kultur"],
  ["Welchen historischen Ort würdest du besuchen?","In welcher Epoche würdest du leben wollen?","kultur"],
  ["Welches Theaterstück hast du gesehen?","Welches Stück würdest du gern sehen?","kultur"],
  ["Welche Redewendung benutzt du oft?","Welches Sprichwort findest du unsinnig?","kultur"],
  ["Welchen Dialekt magst du?","Welchen Dialekt verstehst du nicht?","kultur"],
  ["Welche Tradition hältst du in Ehren?","Welche Tradition findest du überholt?","kultur"],
  ["Welches Land hat die schönste Sprache?","Welches Land hat das beste Essen?","kultur"],
  ["Welche Erfindung hat die Welt am meisten verändert?","Welche Erfindung war ein Fehler?","kultur"],
  ["Welche historische Person würdest du befragen?","Welche Frage würdest du ihr stellen?","kultur"],
  ["Welches Gedicht kennst du noch aus der Schule?","Welchen Text musstest du auswendig lernen?","kultur"],
  ["Welches Handwerk würdest du gern beherrschen?","Welches Handwerk stirbt gerade aus?","kultur"],
  ["Welche Zeitung oder Seite liest du?","Woher bekommst du deine Nachrichten?","kultur"],
  ["Welchen Feiertag aus einem anderen Land findest du gut?","Welchen Brauch würdest du übernehmen?","kultur"],
  ["Welches deutsche Wort erklärt man Ausländern schwer?","Welches Wort fehlt im Deutschen?","kultur"],
  ["Welches Fach würdest du studieren?","Was würdest du unterrichten können?","kultur"],
  ["Welches Wissen aus der Schule nutzt du heute?","Was hast du komplett vergessen?","kultur"],
  ["Welche Ausstellung würdest du besuchen?","Was ist dir in einem Museum zu langweilig?","kultur"],
  ["Welche Zahl oder welches Datum merkst du dir ewig?","Welchen Geburtstag vergisst du immer?","kultur"],
  ["Welches Buch würdest du verschenken?","Welches Buch hat dich verändert?","kultur"],
  ["Welche Fremdsprache kannst du am besten?","In welcher Sprache träumst du?","kultur"],
  ["Welche Kunstform sagt dir am meisten?","Welche Kunstform sagt dir gar nichts?","kultur"],
  ["Was würdest du in einer Zeitkapsel hinterlassen?","Was soll in hundert Jahren noch bekannt sein?","kultur"],
  ["Welches historische Ereignis hast du miterlebt?","Wo warst du bei einem großen Ereignis?","kultur"],
  ["Welche Sportart würdest du bei Olympia schauen?","Welche olympische Disziplin kennst du kaum?","sport"],
  ["Wie viele Kilometer schaffst du am Stück?","Wie viele Kilometer läufst du im Monat?","sport"],
  ["Welche Sportart hält am längsten fit?","Welche Sportart ruiniert die Gelenke?","sport"],
  ["Was ist deine beste Ausrede fürs Nichttrainieren?","Was bringt dich doch noch vom Sofa hoch?","sport"],
  ["Welchen Sport machst du im Urlaub?","Welchen Sport probierst du nur einmal?","sport"],
  ["Welche Sportart würdest du live kommentieren?","Welcher Kommentator nervt dich?","sport"],
  ["Wie viel gibst du im Jahr für Sport aus?","Wie viel hat deine teuerste Sportausrüstung gekostet?","sport"],
  ["Welches Trikot hängt bei dir im Schrank?","Welches Trikot würdest du nie tragen?","sport"],
  ["Wie stehst du morgens fürs Training auf?","Wer weckt dich zum Sport?","sport"],
  ["Welche Verletzung hattest du schon?","Was tut dir beim Sport regelmäßig weh?","sport"],
  ["Was ist dein Lieblingsplatz zum Laufen?","Wo läufst du nie?","sport"],
  ["Welche Sportart passt zu deinem Charakter?","Welche passt zu deinem besten Freund?","sport"],
  ["Wie viele Schritte sind für dich ein guter Tag?","Wie viele Schritte schaffst du an einem faulen Tag?","sport"],
  ["Welchen Sport hast du im Fernsehen entdeckt?","Welche Sportart hast du nie verstanden?","sport"],
  ["Wie oft nimmst du die Treppe statt des Aufzugs?","Wie oft gehst du zu Fuß statt zu fahren?","sport"],
  ["Welches Sportzitat gefällt dir?","Was sagst du dir, wenn es schwer wird?","sport"],
  ["Welche Mannschaftssportart magst du?","Welche Einzelsportart magst du?","sport"],
  ["Was ziehst du an, wenn du joggen gehst?","Welche Schuhe trägst du beim Sport?","sport"],
  ["Wie lange bleibst du nach dem Training noch da?","Wie lange brauchst du zum Umziehen?","sport"],
  ["Welche Sportart würdest du unterrichten können?","Welche Sportart würdest du gern lernen?","sport"],
  ["Wie schlägst du dich beim Tischtennis?","Wie schlägst du dich beim Billard?","sport"],
  ["Welches Fitnessziel hast du erreicht?","Welches Ziel hast du aufgegeben?","sport"],
  ["Welches Lied läuft bei dir zum Feierabend?","Welches Lied startet dein Wochenende?","musik"],
  ["Welche Musik hörst du beim Arbeiten?","Welche Musik lenkt dich beim Arbeiten ab?","musik"],
  ["Welchen Musikstil hören deine Freunde?","Wobei seid ihr euch musikalisch nie einig?","musik"],
  ["Welche Playlist hast du selbst gebaut?","Welche Playlist hörst du am häufigsten?","musik"],
  ["Welches Lied hat dich getröstet?","Welches Lied gibt dir Kraft?","musik"],
  ["Welcher Refrain geht sofort ins Ohr?","Welche Melodie erkennst du nach zwei Tönen?","musik"],
  ["Welche Musik läuft bei euch beim Essen?","Welche Musik läuft bei euch auf Partys?","musik"],
  ["Welchen Musiker findest du als Mensch spannend?","Wessen Lebensgeschichte würdest du lesen?","musik"],
  ["Welches Duett ist gelungen?","Welche Zusammenarbeit hätte es nicht gebraucht?","musik"],
  ["Was war dein erstes Konzert?","Mit wem warst du dort?","musik"],
  ["Welche Musik magst du nur live?","Welche Musik hörst du nur allein?","musik"],
  ["Welches Lied hat dein Handy zuletzt erkannt?","Welches Lied suchst du seit Ewigkeiten?","musik"],
  ["Welches Cover ist besser als das Original?","Welches Original ist unantastbar?","musik"],
  ["Welchen Song hörst du auf Wiederholung?","Welches Lied überspringst du immer?","musik"],
  ["Welche Musik lief auf deiner Abschlussfeier?","Welches Lied verbindest du mit einer Klassenfahrt?","musik"],
  ["Welches Musikinstrument klingt für dich am schönsten?","Welches Instrument nervt dich?","musik"],
  ["Welchen Chor oder welche Band würdest du gern hören?","Wo hast du zuletzt Livemusik gehört?","musik"],
  ["Welche Musik machst du selbst?","Was hast du je in ein Mikrofon gesungen?","musik"],
  ["Welches Album würdest du auf Vinyl kaufen?","Was besitzt du physisch an Musik?","musik"],
  ["Welche Musikrichtung wird in zehn Jahren groß sein?","Welche Musik kommt gerade zurück?","musik"],
  ["Welchen Film würdest du im Freien schauen?","Welchen Film schaust du nur im Dunkeln?","filme"],
  ["Welche Verfilmung hat dich enttäuscht?","Welche Fortsetzung war unnötig?","filme"],
  ["Welche Filmfigur würdest du treffen wollen?","Welche Figur ist dir zu nah an dir selbst?","filme"],
  ["Welchen Film schaut ihr in der Familie?","Welchen Film versteht ihr alle anders?","filme"],
  ["Welcher Film hat dich zum Nachdenken gebracht?","Welcher Film hat dich einfach unterhalten?","filme"],
  ["Welches Genre wählst du am Abend?","Welches Genre meidest du?","filme"],
  ["Welchen Filmklassiker hast du nie gesehen?","Welchen solltest du endlich schauen?","filme"],
  ["Welche Serienfigur würdest du feuern?","Welche Figur verdient eine eigene Serie?","filme"],
  ["Welcher Film ist gut zum Einschlafen?","Bei welchem Film schläfst du garantiert ein?","filme"],
  ["Welchen Film hast du auf einer Reise gesehen?","Welchen Film schaust du im Flugzeug?","filme"],
  ["Welchen Regisseur erkennst du am Stil?","Wessen Filme schaust du blind?","filme"],
  ["Welcher Filmtrailer war besser als der Film?","Welcher Film wurde schlecht beworben?","filme"],
  ["Welche Szene schaust du immer wieder?","Welche Szene überspringst du?","filme"],
  ["Welche Serie hat den besten Vorspann?","Welchen Vorspann überspringst du sofort?","filme"],
  ["Welchen Film würdest du im Unterricht zeigen?","Welchen Film sollte jeder gesehen haben?","filme"],
  ["Welcher Film war deiner Zeit voraus?","Welcher Film ist schlecht gealtert?","filme"],
  ["Wen würdest du dich in einem Film spielen lassen?","Wer spielt deinen besten Freund?","filme"],
  ["Welche Filmwelt wäre unbewohnbar?","In welcher Serienstadt würdest du wohnen?","filme"],
  ["Welchen Film hast du wegen jemandem geschaut?","Wem hast du einen Film aufgedrängt?","filme"],
  ["Welches Spiel hast du im Urlaub gespielt?","Welches Spiel nimmst du auf Reisen mit?","games"],
  ["Welche Spielfigur würdest du als Kostüm tragen?","Welches Spiel würde ein gutes Kostüm hergeben?","games"],
  ["Welches Spiel hast du im Laden entdeckt?","Wer hat dir ein Spiel empfohlen?","games"],
  ["Wie oft startest du ein Spiel neu?","Wie oft hast du einen Spielstand verloren?","games"],
  ["Welcher Spielsound ist dir im Kopf?","Welche Spielmusik hörst du auch ohne Spiel?","games"],
  ["Welches Spiel hast du im Zug gespielt?","Was spielst du beim Warten?","games"],
  ["Welche Spielmechanik nervt dich?","Welche Mechanik findest du genial?","games"],
  ["Welches Spiel würdest du erfinden?","Welches Spiel fehlt auf dem Markt?","games"],
  ["Wie viele Spiele besitzt du?","Wie viele hast du wirklich durchgespielt?","games"],
  ["Welches Spiel spielst du mit deinen Eltern?","Welches Spiel spielst du mit Kindern?","games"],
  ["Welcher Schwierigkeitsgrad ist deiner?","Was machst du, wenn ein Spiel zu schwer wird?","games"],
  ["Welches Spiel hat dich richtig geärgert?","Wo hast du den Controller weggelegt?","games"],
  ["Welches Spiel würdest du im Kino sehen?","Welche Spielgeschichte ist am besten?","games"],
  ["Welchen Spielemoment vergisst du nie?","Welches Ende hat dich überrascht?","games"],
  ["Welche Spielwelt ist am schönsten?","Wo bleibst du nur wegen der Aussicht stehen?","games"],
  ["Welches Spiel hast du verschenkt?","Welches Spiel hast du geschenkt bekommen?","games"],
  ["Wie lange dauert dein längstes Spiel?","Wie lange spielst du an einem Abend?","games"],
  ["Welches Spiel wäre ein gutes Brettspiel?","Welches Brettspiel wäre ein gutes Videospiel?","games"],
  ["Welche Spielereihe verfolgst du seit Jahren?","Welchen Teil fandest du am besten?","games"],
  ["Was spielst du an einem Regentag?","Was spielst du zu zweit?","games"],
  ["Welches Tier würdest du auf einem Foto haben wollen?","Welches Tier hast du zuletzt fotografiert?","tiere"],
  ["Welches Tier bringt dich zum Lachen?","Welches Tiervideo schaust du immer wieder?","tiere"],
  ["Welches Tier hat den besten Schlafplatz?","Wo schläft dein Haustier wirklich?","tiere"],
  ["Welches Tier ist im Haus praktisch?","Welches Tier macht am meisten Arbeit?","tiere"],
  ["Welche Tierart würdest du erforschen?","Über welches Tier weißt du zu wenig?","tiere"],
  ["Welches Tier begegnet dir auf dem Weg zur Arbeit?","Welches Tier siehst du im Garten?","tiere"],
  ["Welches Tier wäre ein guter Kollege?","Welches Tier wäre ein schrecklicher Chef?","tiere"],
  ["Welches Tier hat die schönsten Augen?","Welches Tier hat das schönste Fell?","tiere"],
  ["Welches Tier ist dir im Zoo zu traurig?","Welches Tier gehört nicht in einen Zoo?","tiere"],
  ["Welches Tier würdest du adoptieren?","Welchem Tier würdest du ein Zuhause geben?","tiere"],
  ["Wie reagierst du auf eine Spinne im Zimmer?","Wer entfernt bei euch die Spinnen?","tiere"],
  ["Welches Tier war dein Kuscheltier?","Wie hieß dein Kuscheltier?","tiere"],
  ["Welches Tier hat dich im Urlaub überrascht?","Welchem Tier bist du im Ausland begegnet?","tiere"],
  ["Welches Tier passt in eine kleine Wohnung?","Welches Tier braucht viel Platz?","tiere"],
  ["Welches Tier würdest du reiten?","Auf welchem Tier bist du schon geritten?","tiere"],
  ["Welches Tier ist im Winter am schönsten?","Welches Tier sieht man nur im Sommer?","tiere"],
  ["Welches Tier frisst deine Pflanzen?","Was schützt deinen Garten?","tiere"],
  ["Welche Tiernamen findest du witzig?","Wie würdest du eine Katze nennen?","tiere"],
  ["Welches Tier lebt am längsten?","Welches Tier möchtest du in zehn Jahren noch haben?","tiere"],
  ["Welches Tier würdest du im Film synchronisieren?","Welche Stimme hätte dein Haustier?","tiere"],
  ["Welches Auto würdest du deinen Kindern kaufen?","Welches Auto war dein erstes eigenes?","autos"],
  ["Worauf würdest du beim Auto verzichten?","Worauf achtest du beim Autokauf zuerst?","autos"],
  ["Welche Strecke fährst du am liebsten?","Welche Strecke meidest du?","autos"],
  ["Wie parkst du ein: vorwärts oder rückwärts?","Wo parkst du meistens: Parkhaus oder Straße?","autos"],
  ["Was liegt in deiner Mittelkonsole?","Was hast du im Auto verloren und nie gefunden?","autos"],
  ["Welche Farbe hätte dein Traumauto?","Welche Felgen gefallen dir?","autos"],
  ["Wie oft fährst du zur Tankstelle?","Wie oft kaufst du dort etwas zu essen?","autos"],
  ["Wie schnell fährst du auf der Landstraße?","Wie schnell fährst du wirklich meistens?","autos"],
  ["Welches Auto siehst du am häufigsten?","Welches Auto siehst du zu selten?","autos"],
  ["Welche Fahrhilfe möchtest du nicht mehr missen?","Welche Fahrhilfe schaltest du ab?","autos"],
  ["Wie lange fährst du ohne Pause?","Wie lange dauert bei dir eine Pause?","autos"],
  ["Wer fährt bei euch meistens?","Wer ist der bessere Beifahrer?","autos"],
  ["Was war dein längster Stau?","Wie gehst du mit Stau um?","autos"],
  ["Welches Nutzfahrzeug findest du beeindruckend?","Welches Fahrzeug würdest du gern mal fahren?","autos"],
  ["Was kostet dich das Auto im Monat?","Was hat deine letzte Reparatur gekostet?","autos"],
  ["Welche Automarke fährt deine Familie?","Welche Automarke hattest du zuletzt?","autos"],
  ["Was stört dich an modernen Autos?","Was war früher besser am Auto?","autos"],
  ["Was machst du, wenn die Scheibe vereist ist?","Was hast du im Winter immer im Auto?","autos"],
  ["Welche App nutzt du im Auto?","Wie findest du deinen Weg?","autos"],
  ["Was ist dein Auto-Ritual vor dem Losfahren?","Was machst du als Erstes im Auto?","autos"],
  ["Welche Geschichte erzählst du immer wieder?","Welche Geschichte hat dir jemand oft erzählt?","kultur"],
  ["Welches Museum würdest du eröffnen?","Worüber wüsstest du genug für eine Führung?","kultur"],
  ["Welche Sprache klingt am härtesten?","Welche Sprache klingt am weichsten?","kultur"],
  ["Welches Land würdest du kulturell erkunden?","Welche Kultur fasziniert dich?","kultur"],
  ["Welchen Film über Geschichte fandest du gut?","Welches Thema aus der Geschichte interessiert dich?","kultur"],
  ["Welches Wort benutzt du, das andere nicht kennen?","Welches Wort hast du neu gelernt?","kultur"],
  ["Welchen Podcast über Wissen hörst du?","Woher weißt du unnützes Wissen?","kultur"],
  ["Welche Prüfung war deine schwerste?","Was hast du dafür gelernt?","kultur"],
  ["Welchen Beruf gab es früher, den es heute nicht mehr gibt?","Welcher Beruf verschwindet gerade?","kultur"],
  ["Welches Fest würdest du irgendwo auf der Welt feiern?","Welches Fest hier findest du am schönsten?","kultur"],
  ["Welches Bauwerk würdest du besichtigen?","Welches Bauwerk ist überlaufen?","kultur"],
  ["Welchen Roman würdest du verfilmen?","Welche Figur aus einem Buch magst du?","kultur"],
  ["Was liest du vor dem Einschlafen?","Welches Buch möchtest du als Nächstes lesen?","kultur"],
  ["Welchen Kurs würdest du belegen?","Was würdest du an einer Volkshochschule lernen?","kultur"],
  ["Welche Erfindung fehlt der Menschheit?","Was sollte längst gelöst sein?","kultur"],
  ["Welche Nachricht hat dich zuletzt beschäftigt?","Worüber redest du gerade oft?","kultur"],
  ["Welches Sprichwort stimmt aus deiner Sicht?","Welches stimmt überhaupt nicht?","kultur"],
  ["Welchen Ort in Deutschland sollte jeder sehen?","Welchen Ort im Ausland?","kultur"],
  ["Welches Datum kennst du aus der Geschichte?","Welches Jahr würdest du besuchen?","kultur"],
  ["Welche Handschrift hast du?","Wie sieht deine Unterschrift aus?","kultur"],
  ["Welchen Brief hast du aufgehoben?","Wem würdest du einen Brief schreiben?","kultur"],
  ["Welche Tradition führst du in deiner Familie fort?","Welche Tradition beginnst du neu?","kultur"],
  ["Was macht für dich Heimat aus?","Wo fühlst du dich fremd?","kultur"],
  ["Welche Serie läuft bei dir nebenbei?","Welche Serie verlangt deine volle Aufmerksamkeit?","filme"],
  ["Welche Seite besuchst du täglich?","Welche Seite hast du dir abgewöhnt?","medien"]
];
