/* Die Fragen fuer Mind-Match.
   Jeder Eintrag: [Frage, Kategorie, Stufe].

   Jede Kategorie hat genau 25 Fragen: fuenf Stufen mit je fuenf Fragen.
   Die Stufe sagt, wie viele Antworten ernsthaft in Frage kommen - je weniger,
   desto wahrscheinlicher trifft man den King:

     1  sehr viele  - ein Treffer waere Zufall      ("Nenne ein Tier")
     2  viele       - es gibt schon Lieblinge       ("Nenne ein Tier im Wald")
     3  begrenzt    - die Auswahl wird ueberschaubar("Nenne ein Tier mit Fell")
     4  wenige      - kaum noch Ausweichmoeglichkeit("Nenne ein Raubtier")
     5  Zwickmuehle - zwei bis vier Antworten       ("Hund oder Katze?")

   Weil jede Stufe gleich viele Fragen hat, geht der Anstieg bei jeder
   Rundenlaenge sauber auf: eine Runde beginnt immer harmlos und endet immer
   in der Zwickmuehle. */
const KATEGORIEN=[
  {id:"zahlen",name:"Zahlen & Mengen",emoji:"🔢"},
  {id:"alltag",name:"Alltag & Routine",emoji:"🏠"},
  {id:"essen",name:"Essen & Trinken",emoji:"🍽️"},
  {id:"orte",name:"Orte & Reisen",emoji:"🌍"},
  {id:"menschen",name:"Menschen",emoji:"👥"},
  {id:"ich",name:"Über dich",emoji:"🙂"},
  {id:"dinge",name:"Dinge & Geld",emoji:"💶"},
  {id:"arbeit",name:"Arbeit & Schule",emoji:"💼"},
  {id:"medien",name:"Internet & Apps",emoji:"📱"},
  {id:"feste",name:"Feste & Jahreszeiten",emoji:"🎉"},
  {id:"sport",name:"Sport",emoji:"⚽"},
  {id:"musik",name:"Musik",emoji:"🎵"},
  {id:"filme",name:"Filme & Serien",emoji:"🎬"},
  {id:"games",name:"Games",emoji:"🎮"},
  {id:"tiere",name:"Tiere",emoji:"🐾"},
  {id:"autos",name:"Autos & Fahren",emoji:"🚗"},
  {id:"kultur",name:"Kultur & Wissen",emoji:"📚"}
];

/* Nach Kategorie und darin nach Stufe geordnet. */
const FRAGEN=[
  /* --- zahlen --- */
  ["Nenne eine Zahl zwischen 1 und 100","zahlen",1],
  ["Nenne eine große Zahl","zahlen",1],
  ["Nenne eine dreistellige Zahl","zahlen",1],
  ["Nenne eine Hausnummer","zahlen",1],
  ["Nenne ein Jahr","zahlen",1],
  ["Nenne eine runde Zahl","zahlen",2],
  ["Nenne eine Zahl zwischen 1 und 20","zahlen",2],
  ["Nenne eine Uhrzeit","zahlen",2],
  ["Nenne eine Zahl aus dem Einmaleins","zahlen",2],
  ["Nenne eine Zahl, die man oft im Sport hört","zahlen",2],
  ["Nenne eine Zahl zwischen 1 und 10","zahlen",3],
  ["Nenne eine Glückszahl","zahlen",3],
  ["Nenne eine Unglückszahl","zahlen",3],
  ["Nenne die Anzahl der Beine eines Tieres","zahlen",3],
  ["Nenne eine Zahl auf einer Uhr","zahlen",3],
  ["Nenne eine Zahl zwischen 1 und 5","zahlen",4],
  ["Nenne eine einstellige Primzahl","zahlen",4],
  ["Nenne eine gerade Zahl unter 10","zahlen",4],
  ["Nenne eine ungerade Zahl unter 10","zahlen",4],
  ["Nenne eine Zahl auf einem Würfel","zahlen",4],
  ["Kopf oder Zahl?","zahlen",5],
  ["Nenne eine Zahl zwischen 1 und 3","zahlen",5],
  ["Gerade oder ungerade?","zahlen",5],
  ["Eins oder zwei?","zahlen",5],
  ["Nenne eine Zahl zwischen 1 und 4","zahlen",5],
  /* --- alltag --- */
  ["Nenne etwas, das du heute gemacht hast","alltag",1],
  ["Nenne etwas, das im Bad steht","alltag",1],
  ["Nenne etwas, das man jeden Tag benutzt","alltag",1],
  ["Nenne ein Geräusch am Morgen","alltag",1],
  ["Nenne etwas, das in einer Schublade liegt","alltag",1],
  ["Nenne etwas, das man beim Aufräumen findet","alltag",2],
  ["Nenne etwas, das oft kaputtgeht","alltag",2],
  ["Nenne eine Hausarbeit","alltag",2],
  ["Nenne etwas, das man ständig vergisst","alltag",2],
  ["Nenne etwas, das im Flur hängt","alltag",2],
  ["Nenne etwas, das im Kühlschrank steht","alltag",3],
  ["Nenne etwas, das man zum Zähneputzen braucht","alltag",3],
  ["Nenne etwas, das man morgens als Erstes macht","alltag",3],
  ["Nenne etwas, das im Bett liegt","alltag",3],
  ["Nenne etwas, das man abends ausschaltet","alltag",3],
  ["Nenne etwas, das man beim Verlassen der Wohnung mitnimmt","alltag",4],
  ["Nenne etwas, das man vor dem Schlafen macht","alltag",4],
  ["Nenne etwas, das jeden Morgen klingelt","alltag",4],
  ["Nenne etwas, das auf dem Küchentisch steht","alltag",4],
  ["Nenne etwas, das man nach dem Duschen braucht","alltag",4],
  ["Duschst du morgens oder abends?","alltag",5],
  ["Zahnpasta: von unten oder aus der Mitte?","alltag",5],
  ["Toilettenpapier: nach vorn oder nach hinten?","alltag",5],
  ["Fenster nachts: auf oder zu?","alltag",5],
  ["Schuhe: links oder rechts zuerst?","alltag",5],
  /* --- essen --- */
  ["Nenne ein Essen","essen",1],
  ["Nenne ein Getränk","essen",1],
  ["Nenne eine Zutat","essen",1],
  ["Nenne etwas, das man im Supermarkt kauft","essen",1],
  ["Nenne eine Frucht","essen",1],
  ["Nenne ein Gemüse","essen",2],
  ["Nenne eine Süßigkeit","essen",2],
  ["Nenne ein Frühstück","essen",2],
  ["Nenne ein Gericht aus dem Ausland","essen",2],
  ["Nenne etwas, das man kalt isst","essen",2],
  ["Nenne einen Pizzabelag","essen",3],
  ["Nenne eine Eissorte","essen",3],
  ["Nenne etwas, das man aufs Brot legt","essen",3],
  ["Nenne eine Beilage","essen",3],
  ["Nenne ein Gewürz","essen",3],
  ["Nenne etwas, das man zu Pommes isst","essen",4],
  ["Nenne etwas, das in eine Suppe kommt","essen",4],
  ["Nenne ein Getränk zum Frühstück","essen",4],
  ["Nenne etwas, das man grillt","essen",4],
  ["Nenne einen Kuchen","essen",4],
  ["Pommes: Ketchup oder Mayo?","essen",5],
  ["Süß oder salzig?","essen",5],
  ["Ananas auf Pizza: ja oder nein?","essen",5],
  ["Kaffee oder Tee?","essen",5],
  ["Nutella: dick oder dünn?","essen",5],
  /* --- orte --- */
  ["Nenne ein Land","orte",1],
  ["Nenne eine Stadt","orte",1],
  ["Nenne einen Ort, an den man reist","orte",1],
  ["Nenne einen Raum in einer Wohnung","orte",1],
  ["Nenne einen Ort, an dem viele Menschen sind","orte",1],
  ["Nenne ein Land in Europa","orte",2],
  ["Nenne eine deutsche Großstadt","orte",2],
  ["Nenne ein Urlaubsland","orte",2],
  ["Nenne eine Sehenswürdigkeit","orte",2],
  ["Nenne einen Ort, an dem man wartet","orte",2],
  ["Nenne eine Hauptstadt","orte",3],
  ["Nenne eine Insel","orte",3],
  ["Nenne ein Gebirge","orte",3],
  ["Nenne einen Ort am Wasser","orte",3],
  ["Nenne einen Ort, an dem man leise sein muss","orte",3],
  ["Nenne ein Nachbarland von Deutschland","orte",4],
  ["Nenne ein Bundesland","orte",4],
  ["Nenne einen Fluss","orte",4],
  ["Nenne einen Ozean","orte",4],
  ["Nenne einen Kontinent","orte",4],
  ["Berge oder Meer?","orte",5],
  ["Stadt oder Land?","orte",5],
  ["Fensterplatz oder Gangplatz?","orte",5],
  ["Norden oder Süden?","orte",5],
  ["Urlaub: Zelt oder Hotel?","orte",5],
  /* --- menschen --- */
  ["Nenne einen Vornamen","menschen",1],
  ["Nenne einen Nachnamen","menschen",1],
  ["Nenne einen Namen mit A","menschen",1],
  ["Nenne einen Mädchennamen","menschen",1],
  ["Nenne einen Jungennamen","menschen",1],
  ["Nenne einen berühmten Menschen","menschen",2],
  ["Nenne einen Schauspieler","menschen",2],
  ["Nenne einen Sänger oder eine Sängerin","menschen",2],
  ["Nenne einen Spitznamen","menschen",2],
  ["Nenne einen Namen aus einem Märchen","menschen",2],
  ["Nenne einen Fußballspieler","menschen",3],
  ["Nenne einen Comedian","menschen",3],
  ["Nenne eine berühmte Person aus der Geschichte","menschen",3],
  ["Nenne einen berühmten Maler","menschen",3],
  ["Nenne eine Rolle in einer Familie","menschen",3],
  ["Nenne eine berühmte Person mit nur einem Namen","menschen",4],
  ["Nenne einen berühmten Erfinder","menschen",4],
  ["Nenne einen bekannten Moderator","menschen",4],
  ["Nenne einen Beruf, den man im Notfall ruft","menschen",4],
  ["Nenne eine bekannte Familie aus dem Fernsehen","menschen",4],
  ["Mama oder Papa?","menschen",5],
  ["Anrufen oder schreiben?","menschen",5],
  ["Umarmung oder Handschlag?","menschen",5],
  ["Wenige enge oder viele lockere Freunde?","menschen",5],
  ["Streit: sofort klären oder drüber schlafen?","menschen",5],
  /* --- ich --- */
  ["Nenne ein Hobby","ich",1],
  ["Nenne etwas, das du gut kannst","ich",1],
  ["Nenne etwas, das dich glücklich macht","ich",1],
  ["Nenne etwas, das du lernen willst","ich",1],
  ["Nenne eine Lieblingsfarbe","ich",1],
  ["Nenne ein Gefühl","ich",2],
  ["Nenne einen Charakterzug","ich",2],
  ["Nenne ein Talent","ich",2],
  ["Nenne etwas, das gute Laune macht","ich",2],
  ["Nenne etwas, das man übt","ich",2],
  ["Nenne eine schlechte Angewohnheit","ich",3],
  ["Nenne etwas, das man gern aufschiebt","ich",3],
  ["Nenne etwas, das beruhigt","ich",3],
  ["Nenne etwas, das man nach Feierabend macht","ich",3],
  ["Nenne einen Traum, den viele haben","ich",3],
  ["Nenne eine Ausrede","ich",4],
  ["Nenne einen guten Vorsatz fürs neue Jahr","ich",4],
  ["Nenne etwas, wovor viele Angst haben","ich",4],
  ["Nenne einen Wochentag","ich",4],
  ["Nenne eine Eigenschaft, die man an anderen schätzt","ich",4],
  ["Früh aufstehen oder lange schlafen?","ich",5],
  ["Laut oder leise?","ich",5],
  ["Planen oder spontan?","ich",5],
  ["Glas halb voll oder halb leer?","ich",5],
  ["Nie wieder Musik oder nie wieder Filme?","ich",5],
  /* --- dinge --- */
  ["Nenne einen Gegenstand","dinge",1],
  ["Nenne etwas aus Holz","dinge",1],
  ["Nenne etwas, das man kaufen kann","dinge",1],
  ["Nenne etwas, das viel Geld kostet","dinge",1],
  ["Nenne etwas, das man verschenkt","dinge",1],
  ["Nenne etwas, das man ausleiht","dinge",2],
  ["Nenne etwas aus Metall","dinge",2],
  ["Nenne etwas, das leuchtet","dinge",2],
  ["Nenne etwas, das man sammelt","dinge",2],
  ["Nenne etwas, das man reparieren kann","dinge",2],
  ["Nenne etwas, das in der Hosentasche ist","dinge",3],
  ["Nenne etwas, das auf einem Schreibtisch liegt","dinge",3],
  ["Nenne etwas, das jeder zuhause hat","dinge",3],
  ["Nenne etwas im Handschuhfach","dinge",3],
  ["Nenne etwas, das in einer Handtasche liegt","dinge",3],
  ["Nenne etwas, das man nie wegwirft","dinge",4],
  ["Nenne etwas, das im Portemonnaie steckt","dinge",4],
  ["Nenne etwas, das an einem Schlüsselbund hängt","dinge",4],
  ["Nenne etwas, das man zum Schreiben braucht","dinge",4],
  ["Nenne einen Geldschein","dinge",4],
  ["Handy: lautlos oder mit Ton?","dinge",5],
  ["Buch: Papier oder Bildschirm?","dinge",5],
  ["Uhr: analog oder digital?","dinge",5],
  ["Bargeld oder Karte?","dinge",5],
  ["Geschenk: Papier oder Tüte?","dinge",5],
  /* --- arbeit --- */
  ["Nenne einen Beruf","arbeit",1],
  ["Nenne ein Schulfach","arbeit",1],
  ["Nenne etwas, das man im Büro braucht","arbeit",1],
  ["Nenne etwas, das man lernen muss","arbeit",1],
  ["Nenne einen Arbeitsplatz","arbeit",1],
  ["Nenne einen Beruf mit Uniform","arbeit",2],
  ["Nenne einen Beruf im Krankenhaus","arbeit",2],
  ["Nenne ein Werkzeug","arbeit",2],
  ["Nenne etwas, das in einer Schultasche liegt","arbeit",2],
  ["Nenne etwas, das auf einem Zeugnis steht","arbeit",2],
  ["Nenne etwas, das in einem Meeting gesagt wird","arbeit",3],
  ["Nenne einen Beruf, den Kinder werden wollen","arbeit",3],
  ["Nenne etwas, das jeder im Büro macht","arbeit",3],
  ["Nenne einen Grund, sich krankzumelden","arbeit",3],
  ["Nenne etwas, das man in der Pause macht","arbeit",3],
  ["Nenne etwas, das man am Montag nicht mag","arbeit",4],
  ["Nenne einen Satz, den Lehrer oft sagen","arbeit",4],
  ["Nenne etwas, das im Lehrerzimmer steht","arbeit",4],
  ["Nenne einen Beruf mit einem Hut","arbeit",4],
  ["Nenne etwas, das auf jedem Schreibtisch steht","arbeit",4],
  ["Homeoffice oder Büro?","arbeit",5],
  ["Meeting oder E-Mail?","arbeit",5],
  ["Früh anfangen oder spät aufhören?","arbeit",5],
  ["Chef sein oder Chef haben?","arbeit",5],
  ["Pause: allein oder mit Kollegen?","arbeit",5],
  /* --- medien --- */
  ["Nenne eine Webseite","medien",1],
  ["Nenne etwas, das man im Internet sucht","medien",1],
  ["Nenne eine App auf deinem Handy","medien",1],
  ["Nenne etwas, das man online kauft","medien",1],
  ["Nenne einen Videokanal","medien",1],
  ["Nenne eine Social-Media-App","medien",2],
  ["Nenne etwas, das man streamt","medien",2],
  ["Nenne eine Suchmaschine","medien",2],
  ["Nenne einen Handy-Hersteller","medien",2],
  ["Nenne etwas, das man am Handy zu lange macht","medien",2],
  ["Nenne ein Emoji, das man oft benutzt","medien",3],
  ["Nenne eine Nachrichten-App","medien",3],
  ["Nenne einen Browser","medien",3],
  ["Nenne etwas, das den Akku leersaugt","medien",3],
  ["Nenne eine Abkürzung aus dem Chat","medien",3],
  ["Nenne eine App, die fast jeder hat","medien",4],
  ["Nenne die erste App, die man morgens öffnet","medien",4],
  ["Nenne ein Emoji mit einem Gesicht","medien",4],
  ["Nenne einen Grund, warum das WLAN nicht geht","medien",4],
  ["Nenne etwas, das auf jedem Startbildschirm ist","medien",4],
  ["iPhone oder Android?","medien",5],
  ["Hell- oder Dunkelmodus?","medien",5],
  ["Gelesen-Haken: an oder aus?","medien",5],
  ["Story oder Beitrag?","medien",5],
  ["Benachrichtigungen: an oder aus?","medien",5],
  /* --- feste --- */
  ["Nenne ein Fest","feste",1],
  ["Nenne etwas, das man feiert","feste",1],
  ["Nenne ein Geschenk","feste",1],
  ["Nenne einen Monat","feste",1],
  ["Nenne etwas, das man im Sommer macht","feste",1],
  ["Nenne eine Dekoration","feste",2],
  ["Nenne etwas, das es an Weihnachten gibt","feste",2],
  ["Nenne einen Feiertag","feste",2],
  ["Nenne etwas, das man auf einer Party macht","feste",2],
  ["Nenne etwas, das man im Winter anzieht","feste",2],
  ["Nenne ein Weihnachtsessen","feste",3],
  ["Nenne ein Kostüm für Karneval","feste",3],
  ["Nenne ein Weihnachtslied","feste",3],
  ["Nenne etwas, das an Silvester passiert","feste",3],
  ["Nenne einen Brauch","feste",3],
  ["Nenne eine Jahreszeit","feste",4],
  ["Nenne etwas, das auf einem Geburtstagstisch steht","feste",4],
  ["Nenne etwas aus einem Adventskalender","feste",4],
  ["Nenne einen Feiertag im Dezember","feste",4],
  ["Nenne etwas, das man zu Ostern versteckt","feste",4],
  ["Weihnachtsbaum: echt oder künstlich?","feste",5],
  ["Geschenke: Heiligabend oder erster Feiertag?","feste",5],
  ["Silvester: Party oder Couch?","feste",5],
  ["Geburtstag: feiern oder ignorieren?","feste",5],
  ["Karneval: mitmachen oder fliehen?","feste",5],
  /* --- sport --- */
  ["Nenne eine Sportart","sport",1],
  ["Nenne etwas, das man beim Sport anzieht","sport",1],
  ["Nenne einen Ort zum Sporttreiben","sport",1],
  ["Nenne etwas, das man mit einem Ball macht","sport",1],
  ["Nenne ein Sportgerät","sport",1],
  ["Nenne eine Ballsportart","sport",2],
  ["Nenne einen Fußballverein","sport",2],
  ["Nenne eine Sportart aus dem Schulsport","sport",2],
  ["Nenne etwas, das ein Schiedsrichter macht","sport",2],
  ["Nenne einen bekannten Sportler","sport",2],
  ["Nenne eine olympische Disziplin","sport",3],
  ["Nenne eine Wintersportart","sport",3],
  ["Nenne eine Sportart im Fernsehen","sport",3],
  ["Nenne etwas, das man im Fitnessstudio macht","sport",3],
  ["Nenne eine Sportart ohne Ball","sport",3],
  ["Nenne eine Sportart mit einem Schläger","sport",4],
  ["Nenne eine Sportart im Wasser","sport",4],
  ["Nenne etwas, das es bei einer Siegerehrung gibt","sport",4],
  ["Nenne eine Kampfsportart","sport",4],
  ["Nenne eine Sportart für genau zwei Personen","sport",4],
  ["Sommer- oder Wintersport?","sport",5],
  ["Mannschaft oder allein?","sport",5],
  ["Selbst spielen oder zuschauen?","sport",5],
  ["Laufen oder Radfahren?","sport",5],
  ["Training: morgens oder abends?","sport",5],
  /* --- musik --- */
  ["Nenne ein Musikinstrument","musik",1],
  ["Nenne eine Musikrichtung","musik",1],
  ["Nenne einen Song","musik",1],
  ["Nenne eine Band","musik",1],
  ["Nenne etwas, das man beim Musikhören macht","musik",1],
  ["Nenne einen deutschen Musiker","musik",2],
  ["Nenne ein Lied aus deiner Jugend","musik",2],
  ["Nenne ein Instrument mit Saiten","musik",2],
  ["Nenne etwas, das es auf einem Konzert gibt","musik",2],
  ["Nenne einen Musik-Streamingdienst","musik",2],
  ["Nenne ein Lied, das jeder mitsingen kann","musik",3],
  ["Nenne einen Ohrwurm","musik",3],
  ["Nenne eine Boyband oder Girlgroup","musik",3],
  ["Nenne ein Instrument im Orchester","musik",3],
  ["Nenne ein Lied, das auf jeder Hochzeit läuft","musik",3],
  ["Nenne ein englisches Weihnachtslied","musik",4],
  ["Nenne ein Instrument, das man bläst","musik",4],
  ["Nenne ein Lied zum Geburtstag","musik",4],
  ["Nenne einen Ton der Tonleiter","musik",4],
  ["Nenne ein Instrument mit Tasten","musik",4],
  ["Kopfhörer oder Lautsprecher?","musik",5],
  ["Playlist oder Zufall?","musik",5],
  ["Konzert oder Festival?","musik",5],
  ["Mitsingen oder mitwippen?","musik",5],
  ["Musik beim Arbeiten: an oder aus?","musik",5],
  /* --- filme --- */
  ["Nenne einen Film","filme",1],
  ["Nenne eine Serie","filme",1],
  ["Nenne eine Filmfigur","filme",1],
  ["Nenne ein Filmgenre","filme",1],
  ["Nenne etwas, das man beim Filmschauen isst","filme",1],
  ["Nenne einen Zeichentrickfilm","filme",2],
  ["Nenne eine Serie aus deiner Kindheit","filme",2],
  ["Nenne einen Superhelden","filme",2],
  ["Nenne einen Actionfilm","filme",2],
  ["Nenne einen Streamingdienst","filme",2],
  ["Nenne einen Weihnachtsfilm","filme",3],
  ["Nenne einen Disney-Film","filme",3],
  ["Nenne einen Film, den jeder kennt","filme",3],
  ["Nenne einen Filmsatz, den jeder kennt","filme",3],
  ["Nenne einen Bösewicht aus einem Film","filme",3],
  ["Nenne einen Film mit einer Zahl im Titel","filme",4],
  ["Nenne einen Film, der im Weltall spielt","filme",4],
  ["Nenne eine Filmreihe mit vielen Teilen","filme",4],
  ["Nenne einen Schauspieler aus Actionfilmen","filme",4],
  ["Nenne einen Zeichentrickhund","filme",4],
  ["Kino oder Couch?","filme",5],
  ["Untertitel oder Synchronisation?","filme",5],
  ["Serie am Stück oder Folge für Folge?","filme",5],
  ["Popcorn: süß oder salzig?","filme",5],
  ["Horror oder Komödie?","filme",5],
  /* --- games --- */
  ["Nenne ein Spiel","games",1],
  ["Nenne ein Brettspiel","games",1],
  ["Nenne etwas, das man zum Spielen braucht","games",1],
  ["Nenne ein Kartenspiel","games",1],
  ["Nenne ein Spiel für draußen","games",1],
  ["Nenne ein Handyspiel","games",2],
  ["Nenne eine Spielkonsole","games",2],
  ["Nenne ein Spiel für zwei Personen","games",2],
  ["Nenne eine Figur aus einem Videospiel","games",2],
  ["Nenne ein Spiel aus deiner Kindheit","games",2],
  ["Nenne ein Spiel, das jeder kennt","games",3],
  ["Nenne ein Spiel für Silvester","games",3],
  ["Nenne eine Spielfigur aus einem Brettspiel","games",3],
  ["Nenne etwas, das man bei einem Spiel gewinnt","games",3],
  ["Nenne ein Spiel mit Würfeln","games",3],
  ["Nenne eine Farbe beim Kartenspiel","games",4],
  ["Nenne eine Figur beim Schach","games",4],
  ["Nenne ein Spiel mit Buchstaben","games",4],
  ["Nenne etwas, das auf einem Spielbrett steht","games",4],
  ["Nenne ein Spiel für eine Party","games",4],
  ["Controller oder Tastatur?","games",5],
  ["Allein oder zu zweit spielen?","games",5],
  ["Handy oder Konsole?","games",5],
  ["Schwer oder leicht?","games",5],
  ["Brettspiel oder Videospiel?","games",5],
  /* --- tiere --- */
  ["Nenne ein Tier","tiere",1],
  ["Nenne ein Haustier","tiere",1],
  ["Nenne ein Tier im Zoo","tiere",1],
  ["Nenne ein Tier auf dem Bauernhof","tiere",1],
  ["Nenne ein Insekt","tiere",1],
  ["Nenne ein Tier im Wald","tiere",2],
  ["Nenne ein Tier im Meer","tiere",2],
  ["Nenne einen Vogel","tiere",2],
  ["Nenne ein großes Tier","tiere",2],
  ["Nenne ein kleines Tier","tiere",2],
  ["Nenne ein Tier, das fliegen kann","tiere",3],
  ["Nenne ein Tier mit Fell","tiere",3],
  ["Nenne ein Tier aus einem Kinderbuch","tiere",3],
  ["Nenne ein Tier, vor dem viele Angst haben","tiere",3],
  ["Nenne ein Tier mit Streifen","tiere",3],
  ["Nenne ein Tier, das im Winter schläft","tiere",4],
  ["Nenne ein Tier, das Eier legt","tiere",4],
  ["Nenne ein Raubtier","tiere",4],
  ["Nenne ein Tier aus Afrika","tiere",4],
  ["Nenne ein Tier, das man reiten kann","tiere",4],
  ["Hund oder Katze?","tiere",5],
  ["Vogel oder Fisch?","tiere",5],
  ["Löwe oder Tiger?","tiere",5],
  ["Pferd oder Kuh?","tiere",5],
  ["Spinne: rausbringen oder wegrennen?","tiere",5],
  /* --- autos --- */
  ["Nenne eine Automarke","autos",1],
  ["Nenne etwas, das man am Auto sieht","autos",1],
  ["Nenne ein Fahrzeug","autos",1],
  ["Nenne eine Autofarbe","autos",1],
  ["Nenne etwas, das es an einer Tankstelle gibt","autos",1],
  ["Nenne etwas, das im Auto liegt","autos",2],
  ["Nenne ein Verkehrsschild","autos",2],
  ["Nenne etwas, das beim Autofahren nervt","autos",2],
  ["Nenne eine teure Automarke","autos",2],
  ["Nenne etwas, das man beim Einsteigen macht","autos",2],
  ["Nenne eine deutsche Automarke","autos",3],
  ["Nenne eine Automarke aus Italien","autos",3],
  ["Nenne ein Auto, das jeder kennt","autos",3],
  ["Nenne einen Oldtimer","autos",3],
  ["Nenne etwas, das ein Auto zum Fahren braucht","autos",3],
  ["Nenne ein Teil am Rad","autos",4],
  ["Nenne etwas, das im Kofferraum liegt","autos",4],
  ["Nenne einen Grund für einen Stau","autos",4],
  ["Nenne etwas, das beim TÜV geprüft wird","autos",4],
  ["Nenne ein Warnlicht im Auto","autos",4],
  ["Automatik oder Handschaltung?","autos",5],
  ["Fahren oder mitfahren?","autos",5],
  ["Schnell oder sparsam?","autos",5],
  ["Auto: schwarz oder weiß?","autos",5],
  ["Elektro oder Benzin?","autos",5],
  /* --- kultur --- */
  ["Nenne ein Buch","kultur",1],
  ["Nenne eine Sprache","kultur",1],
  ["Nenne etwas, das man in der Schule lernt","kultur",1],
  ["Nenne eine Erfindung","kultur",1],
  ["Nenne etwas aus einem Museum","kultur",1],
  ["Nenne eine berühmte Stadt in der Geschichte","kultur",2],
  ["Nenne etwas, das man in einer Bibliothek findet","kultur",2],
  ["Nenne eine Weltreligion","kultur",2],
  ["Nenne ein berühmtes Bauwerk","kultur",2],
  ["Nenne einen Beruf in der Kunst","kultur",2],
  ["Nenne ein Märchen","kultur",3],
  ["Nenne ein Buch, das man in der Schule liest","kultur",3],
  ["Nenne ein Gedicht","kultur",3],
  ["Nenne einen deutschen Dichter","kultur",3],
  ["Nenne ein berühmtes Gemälde","kultur",3],
  ["Nenne ein Wort, das es nur im Deutschen gibt","kultur",4],
  ["Nenne ein Sprichwort","kultur",4],
  ["Nenne einen Planeten","kultur",4],
  ["Nenne ein Weltwunder","kultur",4],
  ["Nenne einen griechischen Gott","kultur",4],
  ["Buch oder Film?","kultur",5],
  ["Museum oder Konzert?","kultur",5],
  ["Theater: ja oder nein?","kultur",5],
  ["Gedicht oder Lied?","kultur",5],
  ["Hochdeutsch oder Dialekt?","kultur",5],
];
