/* Die Fragen fuer Mind-Match.
   Jeder Eintrag: [Frage, Kategorie, Schwierigkeit].
   Vier Schwierigkeitsstufen, gemessen daran, wie viele Antworten ernsthaft
   in Frage kommen:
     1  sehr viele - ein Treffer beim King waere Zufall
     2  viele, aber es gibt schon Lieblingsantworten
     3  wenige naheliegende - hier wird es eng
     4  die Zwickmuehle: zwei bis vier Antworten, ein Treffer ist fast
        unvermeidbar ("Hund oder Katze?", "Nenne eine Zahl zwischen 1 und 3")
   Jede Runde zieht aus allen Stufen und sortiert von leicht nach schwer.
   So faengt es harmlos an und wird zum Schluss zur Zerreissprobe. */
const KATEGORIEN=[
  {id:"zahlen",name:"Zahlen & Mengen",emoji:"🔢"},
  {id:"alltag",name:"Alltag & Routine",emoji:"🏠"},
  {id:"essen",name:"Essen & Trinken",emoji:"🍽️"},
  {id:"orte",name:"Orte & Reisen",emoji:"🌍"},
  {id:"menschen",name:"Menschen",emoji:"👥"},
  {id:"ich",name:"Über dich",emoji:"🙂"},
  {id:"dinge",name:"Dinge & Geld",emoji:"💶"},
  {id:"arbeit",name:"Arbeit & Schule",emoji:"💼"},
  {id:"medien",name:"Internet & Apps",emoji:"📱"},
  {id:"feste",name:"Feste & Jahreszeiten",emoji:"🎉"},
  {id:"sport",name:"Sport",emoji:"⚽"},
  {id:"musik",name:"Musik",emoji:"🎵"},
  {id:"filme",name:"Filme & Serien",emoji:"🎬"},
  {id:"games",name:"Games",emoji:"🎮"},
  {id:"tiere",name:"Tiere",emoji:"🐾"},
  {id:"autos",name:"Autos & Fahren",emoji:"🚗"},
  {id:"kultur",name:"Kultur & Wissen",emoji:"📚"}
];

const FRAGEN=[
  ["Nenne eine Zahl zwischen 1 und 100","zahlen",1],
  ["Nenne eine dreistellige Zahl","zahlen",1],
  ["Nenne ein Jahr im 20. Jahrhundert","zahlen",1],
  ["Nenne eine gerade Zahl unter 50","zahlen",2],
  ["Nenne eine Zahl, die auf 7 endet","zahlen",2],
  ["Nenne eine Uhrzeit am Nachmittag","zahlen",2],
  ["Nenne einen Monat mit 31 Tagen","zahlen",2],
  ["Nenne eine Hausnummer","zahlen",2],
  ["Nenne eine Zahl zwischen 1 und 5","zahlen",3],
  ["Nenne eine Glückszahl","zahlen",3],
  ["Nenne eine Zahl, die jeder kennt","zahlen",3],
  ["Nenne ein Alter, in dem sich viel ändert","zahlen",2],
  ["Nenne eine Temperatur im Sommer","zahlen",2],
  ["Nenne einen Preis unter 20 Euro","zahlen",1],
  ["Nenne eine Schulnote","zahlen",2],
  ["Nenne die Anzahl der Beine eines Tieres","zahlen",3],
  ["Nenne eine Zahl über 1000","zahlen",1],
  ["Nenne eine Zahl im Einmaleins","zahlen",2],
  ["Nenne eine Trikotnummer","zahlen",2],
  ["Nenne eine Zahl auf einem Würfel","zahlen",3],
  ["Nenne eine Postleitzahl","zahlen",1],
  ["Nenne eine Zahl, die im Sport vorkommt","zahlen",2],
  ["Nenne etwas, das man morgens macht","alltag",1],
  ["Nenne etwas, das in einer Schublade liegt","alltag",1],
  ["Nenne eine Hausarbeit","alltag",1],
  ["Nenne etwas, das man vor dem Schlafen macht","alltag",2],
  ["Nenne etwas, das in jedem Badezimmer steht","alltag",2],
  ["Nenne etwas, das man täglich benutzt","alltag",2],
  ["Nenne etwas, das man beim Einkaufen vergisst","alltag",2],
  ["Nenne etwas, das in einer Küche steht","alltag",1],
  ["Nenne etwas, das man zum Zähneputzen braucht","alltag",3],
  ["Nenne etwas, das laut ist","alltag",2],
  ["Nenne etwas, das man verlieren kann","alltag",1],
  ["Nenne etwas, das man an der Wand aufhängt","alltag",2],
  ["Nenne etwas, das man wegwirft","alltag",2],
  ["Nenne etwas, das man sammelt","alltag",1],
  ["Nenne etwas, das man beim Aufstehen als Erstes sieht","alltag",3],
  ["Nenne etwas, das nervt","alltag",2],
  ["Nenne etwas, das man am Wochenende macht","alltag",1],
  ["Nenne etwas, das in einem Flur steht","alltag",2],
  ["Nenne etwas, das man bügelt","alltag",2],
  ["Nenne etwas, das im Kühlschrank steht","alltag",3],
  ["Nenne etwas, das man reparieren kann","alltag",1],
  ["Nenne etwas, das man aufräumt","alltag",2],
  ["Nenne ein Gericht mit Nudeln","essen",1],
  ["Nenne etwas, das man zum Frühstück isst","essen",1],
  ["Nenne eine Gemüsesorte","essen",2],
  ["Nenne eine Obstsorte","essen",2],
  ["Nenne einen Pizzabelag","essen",3],
  ["Nenne eine Süßigkeit","essen",2],
  ["Nenne ein Getränk ohne Alkohol","essen",2],
  ["Nenne etwas, das man aufs Brot legt","essen",3],
  ["Nenne ein Fast-Food-Gericht","essen",1],
  ["Nenne ein Gewürz","essen",2],
  ["Nenne eine Käsesorte","essen",2],
  ["Nenne ein Gericht aus dem Ausland","essen",1],
  ["Nenne eine Eissorte","essen",3],
  ["Nenne eine Suppe","essen",2],
  ["Nenne etwas, das man grillt","essen",2],
  ["Nenne einen Kuchen","essen",1],
  ["Nenne eine Beilage","essen",3],
  ["Nenne etwas Scharfes","essen",2],
  ["Nenne ein Getränk mit Alkohol","essen",1],
  ["Nenne eine Brotsorte","essen",2],
  ["Nenne etwas, das man in die Pfanne haut","essen",3],
  ["Nenne einen Snack fürs Kino","essen",2],
  ["Nenne ein Land in Europa","orte",1],
  ["Nenne eine Hauptstadt","orte",1],
  ["Nenne eine deutsche Großstadt","orte",2],
  ["Nenne ein Urlaubsland","orte",2],
  ["Nenne einen Ort am Wasser","orte",2],
  ["Nenne ein Land in Afrika","orte",1],
  ["Nenne ein Nachbarland von Deutschland","orte",3],
  ["Nenne eine Insel","orte",2],
  ["Nenne einen Ort, an dem es laut ist","orte",2],
  ["Nenne einen Ort, an dem viele Menschen sind","orte",1],
  ["Nenne ein Gebirge","orte",2],
  ["Nenne ein Bundesland","orte",3],
  ["Nenne einen Ort, an dem man wartet","orte",1],
  ["Nenne eine Sehenswürdigkeit","orte",2],
  ["Nenne einen Ort, an dem man leise sein muss","orte",2],
  ["Nenne ein Land in Asien","orte",1],
  ["Nenne einen Fluss","orte",3],
  ["Nenne einen Ort im Winterurlaub","orte",2],
  ["Nenne einen Raum in einer Wohnung","orte",1],
  ["Nenne ein Geschäft in der Innenstadt","orte",2],
  ["Nenne einen Ozean","orte",3],
  ["Nenne einen Ort, an dem man sich verirrt","orte",2],
  ["Nenne einen Vornamen","menschen",1],
  ["Nenne ein Familienmitglied","menschen",2],
  ["Nenne einen berühmten Menschen","menschen",2],
  ["Nenne einen Nachnamen","menschen",1],
  ["Nenne einen berühmten Erfinder","menschen",3],
  ["Nenne eine Rolle in einer Familie","menschen",2],
  ["Nenne einen Mädchennamen","menschen",1],
  ["Nenne einen Jungennamen","menschen",1],
  ["Nenne einen Spitznamen","menschen",2],
  ["Nenne einen Beruf, den man im Notfall ruft","menschen",3],
  ["Nenne einen Sänger oder eine Sängerin","menschen",2],
  ["Nenne einen Schauspieler","menschen",2],
  ["Nenne eine berühmte Person aus der Geschichte","menschen",1],
  ["Nenne eine berühmte Person mit nur einem Namen","menschen",3],
  ["Nenne einen Fußballspieler","menschen",2],
  ["Nenne einen berühmten Maler","menschen",2],
  ["Nenne einen Namen mit A","menschen",1],
  ["Nenne einen Namen aus einem Märchen","menschen",2],
  ["Nenne einen bekannten Moderator","menschen",3],
  ["Nenne einen Comedian","menschen",2],
  ["Nenne einen Namen, den du oft hörst","menschen",1],
  ["Nenne eine bekannte Familie aus dem Fernsehen","menschen",2],
  ["Nenne eine Eigenschaft, die du magst","ich",2],
  ["Nenne eine schlechte Angewohnheit","ich",2],
  ["Nenne ein Hobby","ich",1],
  ["Nenne ein Gefühl","ich",2],
  ["Nenne etwas, wovor viele Angst haben","ich",3],
  ["Nenne etwas, das dich beruhigt","ich",2],
  ["Nenne etwas, das du gut kannst","ich",1],
  ["Nenne etwas, das man übt","ich",2],
  ["Nenne einen Traum, den viele haben","ich",2],
  ["Nenne eine Ausrede","ich",3],
  ["Nenne etwas, das dich glücklich macht","ich",1],
  ["Nenne etwas, das gute Laune macht","ich",2],
  ["Nenne einen Charakterzug","ich",2],
  ["Nenne etwas, das du lernen willst","ich",1],
  ["Nenne einen guten Vorsatz fürs neue Jahr","ich",3],
  ["Nenne etwas, das man aufschiebt","ich",2],
  ["Nenne eine Lieblingsfarbe","ich",1],
  ["Nenne eine Jahreszeit","ich",2],
  ["Nenne einen Wochentag","ich",3],
  ["Nenne etwas, das man nach Feierabend macht","ich",2],
  ["Nenne etwas, das man gern isst, wenn es einem schlecht geht","ich",1],
  ["Nenne ein Talent","ich",2],
  ["Nenne etwas, das in einer Handtasche liegt","dinge",1],
  ["Nenne etwas, das man immer dabei hat","dinge",2],
  ["Nenne etwas aus Metall","dinge",2],
  ["Nenne etwas aus Holz","dinge",1],
  ["Nenne etwas, das man in der Hosentasche hat","dinge",3],
  ["Nenne etwas, das teuer ist","dinge",2],
  ["Nenne etwas, das man verschenkt","dinge",1],
  ["Nenne etwas, das kaputtgehen kann","dinge",2],
  ["Nenne ein Möbelstück","dinge",2],
  ["Nenne etwas, das jeder zuhause hat","dinge",3],
  ["Nenne ein Werkzeug","dinge",1],
  ["Nenne etwas, das leuchtet","dinge",2],
  ["Nenne etwas, das man aufbewahrt","dinge",2],
  ["Nenne etwas aus Plastik","dinge",1],
  ["Nenne etwas, das auf einem Schreibtisch liegt","dinge",3],
  ["Nenne ein Kleidungsstück","dinge",2],
  ["Nenne etwas, das man online bestellt","dinge",1],
  ["Nenne etwas, das man ausleiht","dinge",2],
  ["Nenne etwas, das in jedem Auto liegt","dinge",3],
  ["Nenne etwas, das schwer ist","dinge",2],
  ["Nenne etwas, das man sammelt und nie benutzt","dinge",1],
  ["Nenne etwas aus Glas","dinge",2],
  ["Nenne einen Beruf","arbeit",1],
  ["Nenne ein Schulfach","arbeit",2],
  ["Nenne einen Beruf im Krankenhaus","arbeit",2],
  ["Nenne einen Beruf mit Uniform","arbeit",1],
  ["Nenne einen Beruf, den Kinder werden wollen","arbeit",3],
  ["Nenne etwas, das im Büro steht","arbeit",2],
  ["Nenne einen Handwerksberuf","arbeit",1],
  ["Nenne etwas, das man in einer Bewerbung schreibt","arbeit",2],
  ["Nenne eine Ausrede fürs Zuspätkommen","arbeit",2],
  ["Nenne etwas, das jeder im Büro macht","arbeit",3],
  ["Nenne einen Beruf im Freien","arbeit",1],
  ["Nenne etwas, das man in der Pause macht","arbeit",2],
  ["Nenne einen Studiengang","arbeit",2],
  ["Nenne einen Beruf mit Tieren","arbeit",1],
  ["Nenne etwas, das in einem Meeting gesagt wird","arbeit",3],
  ["Nenne ein Werkzeug im Büro","arbeit",2],
  ["Nenne einen Nebenjob für Schüler","arbeit",1],
  ["Nenne eine Abteilung in einer Firma","arbeit",2],
  ["Nenne etwas, das man am Montag hasst","arbeit",3],
  ["Nenne einen Beruf im Fernsehen","arbeit",2],
  ["Nenne etwas, das man lernt","arbeit",1],
  ["Nenne eine Sache am Arbeitsplatz, die nervt","arbeit",2],
  ["Nenne eine App auf deinem Handy","medien",1],
  ["Nenne ein soziales Netzwerk","medien",2],
  ["Nenne eine Webseite","medien",2],
  ["Nenne etwas, das man googelt","medien",1],
  ["Nenne ein Emoji, das man oft benutzt","medien",3],
  ["Nenne einen Handyhersteller","medien",2],
  ["Nenne etwas, das man online kauft","medien",1],
  ["Nenne einen Streamingdienst","medien",2],
  ["Nenne etwas, das im Internet nervt","medien",2],
  ["Nenne eine App, die jeder hat","medien",3],
  ["Nenne einen Podcast oder Kanal","medien",1],
  ["Nenne ein technisches Gerät","medien",2],
  ["Nenne etwas, das man im Internet lernt","medien",2],
  ["Nenne ein Passwort-Wort, das viele nehmen","medien",1],
  ["Nenne einen Browser","medien",3],
  ["Nenne etwas, das man auf dem Handy speichert","medien",2],
  ["Nenne ein Videoportal","medien",1],
  ["Nenne etwas, das Akku frisst","medien",2],
  ["Nenne eine Nachrichten-App","medien",3],
  ["Nenne etwas, das man teilt","medien",2],
  ["Nenne eine Suchmaschine","medien",1],
  ["Nenne etwas, das man abonniert","medien",2],
  ["Nenne einen Feiertag","feste",1],
  ["Nenne etwas, das zu Weihnachten gehört","feste",2],
  ["Nenne etwas, das es an Ostern gibt","feste",2],
  ["Nenne etwas, das man auf einer Party macht","feste",1],
  ["Nenne ein Weihnachtsessen","feste",3],
  ["Nenne ein Geschenk","feste",2],
  ["Nenne etwas, das man an Silvester macht","feste",1],
  ["Nenne eine Dekoration","feste",2],
  ["Nenne etwas auf einem Weihnachtsmarkt","feste",2],
  ["Nenne ein Kostüm für Karneval","feste",3],
  ["Nenne etwas, das man im Sommer feiert","feste",1],
  ["Nenne etwas auf einem Geburtstagstisch","feste",2],
  ["Nenne etwas, das es auf dem Jahrmarkt gibt","feste",2],
  ["Nenne ein Lied, das auf Feiern läuft","feste",1],
  ["Nenne ein Weihnachtslied","feste",3],
  ["Nenne etwas, das man zu einer Hochzeit mitbringt","feste",2],
  ["Nenne eine Jahreszeit mit Festen","feste",1],
  ["Nenne etwas, das man an Feiertagen isst","feste",2],
  ["Nenne einen Brauch","feste",3],
  ["Nenne etwas, das man auf einem Fest trinkt","feste",2],
  ["Nenne etwas, das man zum Geburtstag schenkt","feste",1],
  ["Nenne etwas, das an einem Feiertag geschlossen ist","feste",2],
  ["Nenne eine Sportart","sport",1],
  ["Nenne eine Ballsportart","sport",2],
  ["Nenne eine Übung aus dem Fitnessstudio","sport",2],
  ["Nenne ein Sportgerät","sport",1],
  ["Nenne eine olympische Disziplin","sport",3],
  ["Nenne einen Fußballverein","sport",2],
  ["Nenne eine Wintersportart","sport",1],
  ["Nenne etwas, das man beim Sport trägt","sport",2],
  ["Nenne eine Sportart ohne Ball","sport",2],
  ["Nenne einen bekannten Sportler","sport",3],
  ["Nenne eine Sportart im Wasser","sport",1],
  ["Nenne etwas in einer Sporttasche","sport",2],
  ["Nenne ein Turnier","sport",2],
  ["Nenne eine Sportart, die man allein macht","sport",1],
  ["Nenne eine Sportart aus dem Schulsport","sport",3],
  ["Nenne etwas, das man nach dem Sport trinkt","sport",2],
  ["Nenne eine Sportart mit Schläger","sport",1],
  ["Nenne eine Verletzung beim Sport","sport",2],
  ["Nenne eine Sportart im Fernsehen","sport",3],
  ["Nenne ein Sportstadion","sport",2],
  ["Nenne etwas, das man beim Laufen hört","sport",1],
  ["Nenne eine Sportart für zwei","sport",2],
  ["Nenne ein Musikinstrument","musik",1],
  ["Nenne eine Musikrichtung","musik",2],
  ["Nenne eine Band","musik",2],
  ["Nenne einen Liedtitel","musik",1],
  ["Nenne ein Lied, das jeder mitsingen kann","musik",3],
  ["Nenne einen Sänger","musik",2],
  ["Nenne etwas, das man auf einem Konzert macht","musik",1],
  ["Nenne ein Instrument mit Saiten","musik",2],
  ["Nenne einen Musiker aus Deutschland","musik",2],
  ["Nenne etwas, das man beim Autofahren hört","musik",1],
  ["Nenne ein Festival","musik",2],
  ["Nenne ein Lied aus deiner Jugend","musik",2],
  ["Nenne ein Instrument, das man bläst","musik",1],
  ["Nenne einen Ohrwurm","musik",3],
  ["Nenne etwas, das auf einer Party läuft","musik",2],
  ["Nenne ein Lied zum Tanzen","musik",1],
  ["Nenne einen Radiosender","musik",2],
  ["Nenne eine Boyband oder Girlgroup","musik",3],
  ["Nenne ein Lied mit einer Farbe im Titel","musik",2],
  ["Nenne etwas, das man zum Musikhören benutzt","musik",1],
  ["Nenne ein Instrument im Orchester","musik",2],
  ["Nenne ein Lied, das auf jeder Hochzeit läuft","musik",3],
  ["Nenne einen Filmtitel","filme",1],
  ["Nenne eine Serie","filme",2],
  ["Nenne einen Zeichentrickfilm","filme",2],
  ["Nenne einen Weihnachtsfilm","filme",3],
  ["Nenne einen Actionfilm","filme",2],
  ["Nenne eine Filmfigur","filme",1],
  ["Nenne einen Bösewicht aus einem Film","filme",2],
  ["Nenne etwas, das man im Kino isst","filme",2],
  ["Nenne einen Film, den jeder kennt","filme",3],
  ["Nenne eine Komödie","filme",1],
  ["Nenne eine Serie zum Einschlafen","filme",2],
  ["Nenne einen Superhelden","filme",2],
  ["Nenne einen Filmklassiker","filme",1],
  ["Nenne einen Disney-Film","filme",3],
  ["Nenne eine Serie mit vielen Staffeln","filme",2],
  ["Nenne ein Filmgenre","filme",1],
  ["Nenne einen Regisseur","filme",2],
  ["Nenne einen Filmsatz, den jeder kennt","filme",3],
  ["Nenne einen Horrorfilm","filme",2],
  ["Nenne eine Serie aus deiner Kindheit","filme",1],
  ["Nenne einen Film mit einer Zahl im Titel","filme",2],
  ["Nenne eine Schauspielerin","filme",2],
  ["Nenne ein Videospiel","games",1],
  ["Nenne ein Brettspiel","games",2],
  ["Nenne ein Kartenspiel","games",2],
  ["Nenne eine Spielkonsole","games",1],
  ["Nenne ein Spiel, das jeder kennt","games",3],
  ["Nenne ein Handyspiel","games",2],
  ["Nenne ein Spiel für draußen","games",1],
  ["Nenne eine Spielfigur","games",2],
  ["Nenne ein Spiel für Kinder","games",2],
  ["Nenne ein Spiel für Silvester","games",3],
  ["Nenne ein Rennspiel","games",1],
  ["Nenne etwas, das man beim Spielen sagt","games",2],
  ["Nenne ein Spiel mit Würfeln","games",2],
  ["Nenne ein Sportspiel","games",1],
  ["Nenne ein Spiel aus deiner Kindheit","games",3],
  ["Nenne ein Spiel für zwei Personen","games",2],
  ["Nenne etwas, das man zum Spielen braucht","games",1],
  ["Nenne ein Spiel ohne Material","games",2],
  ["Nenne eine Spielfigur aus einem Brettspiel","games",3],
  ["Nenne ein Online-Spiel","games",2],
  ["Nenne ein Puzzle oder Knobelspiel","games",1],
  ["Nenne etwas, das man im Spiel sammelt","games",2],
  ["Nenne ein Tier","tiere",1],
  ["Nenne ein Haustier","tiere",2],
  ["Nenne ein Tier mit vier Beinen","tiere",2],
  ["Nenne ein Tier im Zoo","tiere",1],
  ["Nenne ein Tier, das fliegen kann","tiere",3],
  ["Nenne ein Tier im Wasser","tiere",2],
  ["Nenne ein Tier auf dem Bauernhof","tiere",1],
  ["Nenne ein gefährliches Tier","tiere",2],
  ["Nenne ein Insekt","tiere",2],
  ["Nenne ein Tier mit Fell","tiere",3],
  ["Nenne ein Tier aus Afrika","tiere",1],
  ["Nenne einen Vogel","tiere",2],
  ["Nenne ein Tier, das man streichelt","tiere",2],
  ["Nenne ein Tier im Wald","tiere",1],
  ["Nenne ein Tier, vor dem viele Angst haben","tiere",3],
  ["Nenne eine Hunderasse","tiere",2],
  ["Nenne ein Tier mit einem langen Namen","tiere",1],
  ["Nenne ein Tier, das Winterschlaf hält","tiere",2],
  ["Nenne ein Tier aus einem Kinderbuch","tiere",3],
  ["Nenne ein Tier, das Geräusche macht","tiere",2],
  ["Nenne ein Meerestier","tiere",1],
  ["Nenne ein Tier, das niemand zuhause hält","tiere",2],
  ["Nenne eine Automarke","autos",1],
  ["Nenne ein Automodell","autos",2],
  ["Nenne etwas an einem Auto","autos",2],
  ["Nenne ein Fahrzeug","autos",1],
  ["Nenne eine deutsche Automarke","autos",3],
  ["Nenne eine Autofarbe","autos",2],
  ["Nenne etwas, das im Kofferraum liegt","autos",1],
  ["Nenne ein Verkehrsschild","autos",2],
  ["Nenne etwas an einer Tankstelle","autos",2],
  ["Nenne ein Auto, das jeder kennt","autos",3],
  ["Nenne ein Zweirad","autos",1],
  ["Nenne etwas, das man am Auto repariert","autos",2],
  ["Nenne etwas, das beim Fahren nervt","autos",2],
  ["Nenne ein öffentliches Verkehrsmittel","autos",1],
  ["Nenne eine Automarke aus Italien","autos",3],
  ["Nenne etwas im Handschuhfach","autos",2],
  ["Nenne ein großes Fahrzeug","autos",1],
  ["Nenne etwas, das man beim Fahren hört","autos",2],
  ["Nenne einen Oldtimer","autos",3],
  ["Nenne etwas, das man vor der Fahrt prüft","autos",2],
  ["Nenne ein Fahrzeug mit Blaulicht","autos",1],
  ["Nenne eine Automarke aus Asien","autos",2],
  ["Nenne eine Sprache","kultur",1],
  ["Nenne ein Buch","kultur",2],
  ["Nenne einen Autor","kultur",2],
  ["Nenne ein berühmtes Bauwerk","kultur",1],
  ["Nenne ein Märchen","kultur",3],
  ["Nenne eine Erfindung","kultur",2],
  ["Nenne ein Museum oder eine Ausstellung","kultur",1],
  ["Nenne ein Sprichwort","kultur",2],
  ["Nenne eine historische Person","kultur",2],
  ["Nenne ein Buch, das man in der Schule liest","kultur",3],
  ["Nenne etwas, das man im Theater sieht","kultur",1],
  ["Nenne ein Kunstwerk","kultur",2],
  ["Nenne eine Tradition","kultur",2],
  ["Nenne ein Land mit einer eigenen Schrift","kultur",1],
  ["Nenne ein Wort, das es nur im Deutschen gibt","kultur",3],
  ["Nenne einen Fachbegriff aus der Schule","kultur",2],
  ["Nenne eine Wissenschaft","kultur",1],
  ["Nenne eine Epoche","kultur",2],
  ["Nenne ein Gedicht","kultur",3],
  ["Nenne etwas, das man in einer Bibliothek findet","kultur",2],
  ["Nenne eine berühmte Stadt in der Geschichte","kultur",1],
  ["Nenne eine Weltreligion","kultur",2],

  /* Stufe 4 – die Zwickmuehle. Nur zwei bis vier ernsthafte Antworten:
     hier trifft man den King fast zwangslaeufig. Steht am Ende jeder Runde. */
  ["Kopf oder Zahl?","zahlen",4],
  ["Nenne eine Zahl zwischen 1 und 3","zahlen",4],
  ["Gerade oder ungerade?","zahlen",4],
  ["Nenne eine Zahl zwischen 1 und 4","zahlen",4],
  ["Nenne eine einstellige Primzahl","zahlen",4],
  ["Duschst du morgens oder abends?","alltag",4],
  ["Zahnpasta: von unten oder aus der Mitte drücken?","alltag",4],
  ["Toilettenpapier: nach vorn oder nach hinten?","alltag",4],
  ["Fenster nachts: auf oder zu?","alltag",4],
  ["Schuhe anziehen: links oder rechts zuerst?","alltag",4],
  ["Pommes: Ketchup oder Mayo?","essen",4],
  ["Süß oder salzig?","essen",4],
  ["Nutella aufs Brot: dick oder dünn?","essen",4],
  ["Ananas auf Pizza: ja oder nein?","essen",4],
  ["Kaffee oder Tee?","essen",4],
  ["Berge oder Meer?","orte",4],
  ["Stadt oder Land?","orte",4],
  ["Fensterplatz oder Gangplatz?","orte",4],
  ["Norden oder Süden?","orte",4],
  ["Urlaub: Zelt oder Hotel?","orte",4],
  ["Mama oder Papa?","menschen",4],
  ["Anrufen oder schreiben?","menschen",4],
  ["Umarmung oder Handschlag?","menschen",4],
  ["Wenige enge oder viele lockere Freunde?","menschen",4],
  ["Streit: sofort klären oder drüber schlafen?","menschen",4],
  ["Früh aufstehen oder lange schlafen?","ich",4],
  ["Bist du eher laut oder leise?","ich",4],
  ["Planen oder spontan sein?","ich",4],
  ["Glas halb voll oder halb leer?","ich",4],
  ["Nie wieder Musik oder nie wieder Filme?","ich",4],
  ["Handy: lautlos oder mit Ton?","dinge",4],
  ["Buch: Papier oder Bildschirm?","dinge",4],
  ["Geschenk: Papier oder Tüte?","dinge",4],
  ["Uhr: analog oder digital?","dinge",4],
  ["Bargeld oder Karte?","dinge",4],
  ["Homeoffice oder Büro?","arbeit",4],
  ["Meeting oder E-Mail?","arbeit",4],
  ["Früh anfangen oder spät aufhören?","arbeit",4],
  ["Chef sein oder Chef haben?","arbeit",4],
  ["Pause: allein oder mit Kollegen?","arbeit",4],
  ["iPhone oder Android?","medien",4],
  ["Hell- oder Dunkelmodus?","medien",4],
  ["Gelesen-Haken: an oder aus?","medien",4],
  ["Story oder Beitrag?","medien",4],
  ["Benachrichtigungen: an oder aus?","medien",4],
  ["Weihnachtsbaum: echt oder künstlich?","feste",4],
  ["Geschenke: Heiligabend oder erster Feiertag?","feste",4],
  ["Silvester: Party oder Couch?","feste",4],
  ["Geburtstag: feiern oder ignorieren?","feste",4],
  ["Karneval: mitmachen oder fliehen?","feste",4],
  ["Sommer- oder Wintersport?","sport",4],
  ["Mannschaft oder allein?","sport",4],
  ["Selbst spielen oder zuschauen?","sport",4],
  ["Laufen oder Radfahren?","sport",4],
  ["Training: morgens oder abends?","sport",4],
  ["Kopfhörer oder Lautsprecher?","musik",4],
  ["Playlist oder Zufall?","musik",4],
  ["Konzert oder Festival?","musik",4],
  ["Mitsingen oder mitwippen?","musik",4],
  ["Musik beim Arbeiten: an oder aus?","musik",4],
  ["Kino oder Couch?","filme",4],
  ["Untertitel oder Synchronisation?","filme",4],
  ["Serie am Stück oder Folge für Folge?","filme",4],
  ["Popcorn: süß oder salzig?","filme",4],
  ["Horror oder Komödie?","filme",4],
  ["Controller oder Tastatur?","games",4],
  ["Allein oder zu zweit spielen?","games",4],
  ["Handy oder Konsole?","games",4],
  ["Schwerer oder leichter Schwierigkeitsgrad?","games",4],
  ["Brettspiel oder Videospiel?","games",4],
  ["Hund oder Katze?","tiere",4],
  ["Vogel oder Fisch?","tiere",4],
  ["Löwe oder Tiger?","tiere",4],
  ["Spinne: rausbringen oder wegrennen?","tiere",4],
  ["Pferd oder Kuh?","tiere",4],
  ["Automatik oder Handschaltung?","autos",4],
  ["Fahren oder mitfahren?","autos",4],
  ["Schnell oder sparsam?","autos",4],
  ["Auto: schwarz oder weiß?","autos",4],
  ["Elektro oder Benzin?","autos",4],
  ["Buch oder Film?","kultur",4],
  ["Museum oder Konzert?","kultur",4],
  ["Theater: ja oder nein?","kultur",4],
  ["Gedicht oder Lied?","kultur",4],
  ["Hochdeutsch oder Dialekt?","kultur",4],
];
